### ISSUE TITLE
IMPROVE - Error Handling When Deleting an Event

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#10]
## Describe the feature you to improve
* The `deleteEvent` function in the `DashboardViewModel` doesn't handle errors and uses `try?`
* Use a do-catch block for this instead, and show an alert with the error's localized description, if something fails

**Comment by Dishant10** [comment]
Would like to work on this! Please assign it to me. @mikaelacaron

**Comment by mikaelacaron** [comment]
You got this!
