### ISSUE TITLE
Update Czech Localization

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#100]
## Describe the feature you want the app to have that it currently doesn't
* Since the Czech localization was added to the project new strings have been added
* Update to 100% coverage

## Describe alternatives you've considered
* N/A

## Additional context
* Currently at 66% coverage at the time of creating the issue

**Comment by harryheres** [comment]
@mikaelacaron Since I started the Czech localization, I don't mind updating it :)

**Comment by mikaelacaron** [comment]
Awesome thanks!
