### ISSUE TITLE
Update Spanish (Latin America) Localization

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#102]
## Describe the feature you want the app to have that it currently doesn't
* Since the Spanish localization was added to the project new strings have been added
* Update to 100% coverage

## Describe alternatives you've considered
* N/A

## Additional context
* Currently at 88% coverage at the time of creating the issue

**Comment by vikyale** [comment]
Hello! I want to help with this issue :)

**Comment by mikaelacaron** [comment]
You got it!

**Comment by krz** [comment]
Hi, if the original assignee is no longer up for this task, I would like to step in

**Edit**: I just found the Spanish translation has already been completed by someone else (https://github.com/mikaelacaron/Basic-Car-Maintenance/pull/75). I'll work on a Dutch translation tomorrow.

**Comment by mikaelacaron** [comment]
@krz it is up to you, running the project you'll see the Spanish translation is only 50% complete, and the PR you linked is from Oct 5, and the project has changed drastically since then.

You could do the update to Spanish and/or add Dutch

**Comment by mikaelacaron** [comment]
Closing this, because it doesn't need to be an issue, anyone is welcome to update any language whenever
