### ISSUE TITLE
IMPROVE - Fix Label with Large Dynamic Type on `AddMaintenanceView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#104]
## Describe the feature you want to improve
* When the dynamic type size of the `AddMaintenanceView` is at the largest size the date label is cut off by the date picker
* When it's at this size change the label to be above the date picker (so that it isn't cut off anymore, see screenshot)

## Describe alternatives you've considered
* Another alternative is to limit the dynamic type size to the largest that it can go without clipping, [see this article](https://useyourloaf.com/blog/restricting-dynamic-type-sizes/)
   * I would prefer changing the layout before limiting the dynamic type size

![IMG_5494](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/94054d24-04f2-4bd5-9f44-e44a3d046a76)

**Comment by abhinaypratap** [comment]
Hi @mikaelacaron 
I'd like to work on this one.

**Comment by JakeLOLHQ** [comment]
HI @mikaelacaron,
Can I work on this issue?

**Comment by mikaelacaron** [comment]
@abhinaypratap I'll assign it to you! (you are the first to comment), @BuiHuyTam if you could find another issue to work on, that would be great! thanks!
