### ISSUE TITLE
IMPROVE - Order the `ContributorsListView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#105]
## Describe the feature you want to improve
* Order the `ContributorsListView` by developers with the highest contributions and then by the username (alphabetically, A to Z)

## Describe alternatives you've considered
* N/A

## Screenshot
* `ContributorsListView`
![simulator_screenshot_9EE99DDB-BC95-4EF3-9C0F-9E8D6E6F073E](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/1d3aaaad-7822-48c9-a3d1-21b2911f9b64)

**Comment by am2089** [comment]
Can I tackle this issue?

**Comment by mikaelacaron** [comment]
You got it!

**Comment by am2089** [comment]
hey, for this issue do you want a filter tab that lets you alphabetize the list, or list the contributors by highest contributions? and by highest contributions do you mean for this project alone?

**Comment by mikaelacaron** [comment]
Nope! Right now just do it automatically, don't make anew button. That can be a separate issue later on! technically it could be 2

the `contributions` number that comes back now from the API, is for this repo only
