### ISSUE TITLE
IMPROVE - Use ScaledMetric on the `ContributorsListView` for the User's Profile Picture

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#106]
## Describe the feature you want to improve
* Use the `@ScaledMetric` property wrapper to scale the user's profile picture with the dynamic type size
* Scale it with the `.largeTitle`

![IMG_5500](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/ccfd2f3c-db23-47fc-9a04-ba432311d376)

**Comment by rramirez-dev** [comment]
I can can work on this.
