### ISSUE TITLE
FEATURE - Create a Real Time Alert System

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#107]
## Describe the feature you want the app to have that it currently doesn't
* Create a real time alert sheet, inspired from [this video](https://youtu.be/8e1Rbh1ck-U?si=_jUUW_qtkRiYP8fo)
   * Instead of being a custom alert like the video, use a sheet on the `MainTabView` that's in the `BasicCarMaintenanceApp`, using `.presentationDetents([.medium, .large])` for the sheet looking UI
   * Make it so that the sheet can't be swiped down to be dismissed, a user must click the Dismiss button
* Please follow the spec below and let @mikaelacaron know if you have any questions! (tag me in the comment, thanks)
   * Do this in multiple PRs, as shown below

## Describe alternatives you've considered
* N/A

## Additional context
* Get data from Firestore, `alerts` document, which will return an array of alerts. (call the model `RealTimeAlert`)
   * Filter by alerts where `isOn` is `true` (this is something that Mikaela will manually update in Firestore)
   * Use this structure (`actionText` and `actionURL` are optional)

<img width="464" alt="Screenshot 2023-10-16 at 11 27 27 PM" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/5c2beff5-c039-4b96-96dd-4005737551be">

### UI - Creating the Alert (PR 1)
* Use tool bar items for a `Dismiss` button on the leading edge
* Layout the view as shown in the sketch below
   * Center all the elements
   * The action button should stretch the width of the screen with `24` padding on the left and right, and be at least `44` tall
   * When the user clicks on the action button, it should open Safari for whatever website is fetched for `actionURL` (that's in the Firestore response)
   * The sheet shouldn't dismiss when swiping down, a user should have to tap the `Dismiss` button

### Functionality (PR 2)
* On every launch of the app check if there's a message with `isOn` is `true` (only fetch where `isOn` is `true`, don't fetch all of the messages)
   * If you get a message back, show the returned alert on the `MainTabView` (this means it will be presented no matter what)
      * Save the `id` of the message to an array in user defaults  (AppStorage) called `readRealTimeAlerts`
         * Don't show the alert if the `id` of that alert has already been saved to `readRealTimeAlerts` (this is so the alert is not shown every time the user opens the app, it's only shown to them once)
         * ⚠️ I'm thinking save this to user defaults or using SwiftData, but does SwiftData really add any dependencies (like how CoreData did)? let me know in the comments!
   * If you don't get anything back, don't show an alert

### Design
   * Make sure that the alert can scroll
![iPhone 14 Pro - 1](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/7d49281f-f885-4c5c-a9eb-39992f09c541)

**Comment by OmarHegazy93** [comment]
Hi @mikaelacaron I'd like to work on this
