### ISSUE TITLE
IMPROVE - Adding a `ProgressView` to `DashboardView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#108]
## Describe the feature you want to improve
* When the data is being fetched from Firebase, show a `ProgressView` once it's loaded the data will be shown in a list like normal
* Make sure the empty view overlay is still shown after returning 0 results

There would be 3 states:
* Empty, no results
* List, showing one or more `MaintenanceEvent`s
* `ProgressView`, loading data from Firebase

**Comment by aaronthebald** [comment]
I would like to work on this please
@mikaelacaron

**Comment by aaronthebald** [comment]
Sorry I had some stuff come up and I won't be able to get to this right now.

**Comment by mariaykim** [comment]
@mikaelacaron I can work on this!

**Comment by rramirez-dev** [comment]
Can you assign this to me
