### ISSUE TITLE
IMPROVE - Error Handling When Creating an Event

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#11]
## Describe the feature you to improve
* `try? await viewModel.addEvent(event)` is called in the `DashboardView` and doesn't handle if the function throws an error
* Handle this by wrapping it in a do-catch block, and showing an alert if there's an error
* Make sure `viewModel.events.append(event)` is *not* called when the error occurs

**Comment by achi113s** [comment]
I can take care of this one.
