### ISSUE TITLE
IMPROVE - Copyable Text on `SettingsView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#110]
## Describe the feature you want to improve
* Make the version number on the `SettingsView` copyable, so that a user can press and hold on the version number and copy it
* Also center this text in the row

![Simulator Screenshot - iPhone 15 Pro - 2023-10-08 at 23 39 58](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/6444de7b-d314-40a9-9427-03f7bddb4f7d)

**Comment by prabal4546** [comment]
I would love to work on this

**Comment by mikaelacaron** [comment]
Hey @prabal4546 I labeled this `first-timers-only` so that only people new to open source can work on it! Haha and I know you've done open source before. If you could find another issue to work on, that would be great thanks!

**Comment by prabal4546** [comment]
Haha, I guess I picked this too quickly from newly opened issues from yesterday and missed the label. I'll pick something else:)

**Comment by mikaelacaron** [comment]
Thanks for understanding @prabal4546 ! Also for contributing to the project I've created over the years!! ❤️

**Comment by anupdsouza** [comment]
Hey @mikaelacaron, I'd like to take a shot at this.
