### ISSUE TITLE
FEATURE - Save Last Opened Tab

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#111]
## Describe the feature you want the app to have that it currently doesn't
* Open the same tab that the user had open when they closed the app
   * If the user was on the Settings tab when they closed / backgrounded the app, when the app opens again, it should open back to the Settings tab, rather than the default tab
* Track this by using user defaults (AppStorage), with the key `lastTabOpen`

## Describe alternatives you've considered
* N/A

## Additional context
* N/A

**Comment by appfrosch** [comment]
I'd like to give this a shot.

**Comment by mikaelacaron** [comment]
Closed with #115
