### ISSUE TITLE
BUG - Deleting a just recently added vehicle leads to a fatalError

### ISSUE THREAD

**Issue by johnolwamba** [mikaelacaron/Basic-Car-Maintenance#117]
## Describe the bug
* When a vehicle is added in `SettingsView` and a user tries to delete it immediately, we experience a fatal error. This is because the vehicle `id` is not set when the vehicle is added to the `vehicles` array. This is the exact location for the error source in SettingsViewModel:
```
guard let documentId = vehicle.id else {
     fatalError("Event \(vehicle.name) has no document ID.")
}
```

## To Reproduce
1. Go to the 'SettingsView` screen
2. Tap on the button 'Add Vehicle'
3. Swipe right on the just added vehicle and click 'Delete'
4. See crash

## Expected behavior
* Vehicle just added can be deleted immediately without any crash

## Screenshots
* If applicable, add screenshots to help explain your problem.

## Device Info (please complete the following information):
 * Device: [iPhone14 Pro]
 * OS: [e.g. iOS 17.0]
 * App Version [e.g. v1.5]

## Additional Context
* None

**Comment by justinseal** [comment]
Can I try this one?

**Comment by dogra25130** [comment]
@justinseal since you are working on #118, can I pick this one? @mikaelacaron

**Comment by justinseal** [comment]
> @justinseal since you are working on #118, can I pick this one? @mikaelacaron 

Have at it!

**Comment by mikaelacaron** [comment]
@dogra25130 and @justinseal thanks for working this out!
It's one person per issue

**Comment by justinseal** [comment]
No worries at all @mikaelacaron, I think the other issue is a bit more my speed just now anyway. Have at it @dogra25130
