### ISSUE TITLE
IMPROVE - Stringly Typed Firebase Collection Names

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#118]
## Describe the feature you want to improve
* Replace the stringly typed `maintenance_events` with an enum to prevent typos
* Replace the `vehicles` collection too

* Create a new enum `FirebaseCollection` as shown, and use it where needed
```swift
enum FirebaseCollection {
    static let maintenanceEvents = "maintenance_events"
    static let vehicles = "vehicles"
}
```

## Describe alternatives you've considered
* N/A

**Comment by justinseal** [comment]
Ooh! This has my name on it actually!! I can handle this one!

**Comment by peterfriese** [comment]
Excited to see this one land! Just a tiny remark: this should be `Firestore`, not `Firebase`.
