### ISSUE TITLE
IMPROVE - Error Handling When Deleting a Vehicle

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#12]
## Describe the feature you to improve
* In func `deleteVehicle` in the `SettingsViewModel` it doesn't handle if an error is thrown
* Add a do-catch block to show an error in an alert if an error is thrown

**Comment by mishapark** [comment]
Hi, I'd like to work on this one

**Comment by mishapark** [comment]
Please assign this one to me :)

**Comment by mikaelacaron** [comment]
You got it!

**Comment by mikaelacaron** [comment]
Closed with #29
