### ISSUE TITLE
FEATURE  Create App Store listing in App Store Connect

### ISSUE THREAD

**Issue by SuzGupta** [mikaelacaron/Basic-Car-Maintenance#124]
Set up app name, subtitle, keywords, description and all other fields in App Store Connect.

TODO: expand this listing including suggested text for all fields.

**Comment by SuzGupta** [comment]
@mikaelacaron please assign me to this :)

**Comment by DanielZhang111** [comment]
can i get assigned to this?

**Comment by mikaelacaron** [comment]
@DanielZhang111 , @SuzGupta is already assigned! You can collaborate if you'd like but the issue can only count for @SuzGupta for Hacktoberfest

If you want to collab, creating a new thread in GitHub Discussions would be best

**Comment by DanielZhang111** [comment]
Ohhhh thanks. I'm new to this and our teacher is requiring us to get a digital reward and a tree planted to be able to get an A for this term. Thanks tho!!

**Comment by mikaelacaron** [comment]
@DanielZhang111 You're welcome to work on any other issues that are available, and don't have an assignee! I'm going to be adding new issues soon, see the [Discussions tab](https://github.com/mikaelacaron/Basic-Car-Maintenance/discussions) for the latest updates, or follow me on [social media](https://mikaelacaron.com/links).

One note to possibly tell your teacher, is that the tree planted reward is only available to the first 50,000 participants, so if you don't fall into that, hopefully you aren't penalized!

**Comment by DanielZhang111** [comment]
Thanks, but the entire thing about it is that we MUST get the top 50,000 to get 50/50. :( Its a 50 point assignment and if you don't get the reward its either a 25-30 point range :(.

**Comment by mikaelacaron** [comment]
ahhhh, best of luck!! You are welcome to create new issues in this project

**Comment by DanielZhang111** [comment]
Thanks a lot!
