### ISSUE TITLE
IMPROVE - Error Handling When Creating a Vehicle

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#13]
## Describe the feature you to improve
* In func `addVehicle` in the `SettingsViewModel` it doesn't handle if there's an error from Firebase
* Add a do-catch block to show an error in an alert if an error is thrown

**Comment by mishapark** [comment]
Hi, I'd like to work on this one

**Comment by mikaelacaron** [comment]
@samuelowino you create a PR but never commented that you wanted to work on this issue, as request in the [README.md](https://github.com/mikaelacaron/Basic-Car-Maintenance#contributing).

Next time, please make sure you comment on the issue you want to work on, _before_ jumping in and coding. This prevents multiple people working on the same issue.

**Comment by narendrajagne** [comment]
Hi can you assign me this issue ?

**Comment by mikaelacaron** [comment]
This is already done and in review with PR #25 @narendrajagne it's not available

**Comment by tom-ludwig** [comment]
Forgot to asked if you could please assign me to this issue.

**Comment by mikaelacaron** [comment]
@activcoding Be sure to comment on the issue before making a PR next time! thank you!
