### ISSUE TITLE
IMPROVE - Maintenance dashboard Cards spacing

### ISSUE THREAD

**Issue by dogra25130** [mikaelacaron/Basic-Car-Maintenance#135]
## Describe the feature you want to improve
Maintenance without additional notes has empty view. We can remove that empty space.

|With empty space|Without empty space|
|------------------|-----------------------|
|<img src = "https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/32197474/faf8f4d7-f3c2-430d-bbff-0de6eff1e909" width=200>|<img src = "https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/32197474/527682e9-440f-4560-b5cd-92c43749ddce" width=200>|

**Comment by dogra25130** [comment]
I can pick this if you feels it should be done. @mikaelacaron

**Comment by mikaelacaron** [comment]
yeah sounds good! 👍 go for it!
