### ISSUE TITLE
Change the NavigationTitle of the `EditEventDetailView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#136]
## Describe the feature you want to improve
* The `EditEventDetailView` says `Add Maintenance` as the title but instead it should say `Update Maintenance` because we aren't adding something new, but updating values

## Describe alternatives you've considered
* N/A

## Screenshot

https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/6f34035c-5b84-45a4-8aa5-8aaee8acc2a2

**Comment by AakifNadeem** [comment]
Hello @mikaelacaron can you kindly assign it to me
