### ISSUE TITLE
Project Issue / PR Metrics

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#138]
## Description
* I saw this [blog post](https://github.blog/2023-07-19-metrics-for-issues-pull-requests-and-discussions/) that uses GitHub actions to create a report of how many issues / PRs are opened and merged.
* I think it would be super cool to see metrics like this for each week of Hacktoberfest!
   * It could be a markdown file that's created, and then I could post in [Discussions](https://github.com/mikaelacaron/Basic-Car-Maintenance/discussions), it's fine if I have to run this manually (that may actually be preferred too)
## Describe alternatives you've considered
* Later on this could turn into a weekly or monthly action that's run, depending on how busy the project is by the end of Hacktoberfest
* You may need to make a custom script for your own repo, and later let @mikaelacaron  know what's needed to actually fill in the secrets / repo information to actually analyze the Basic Car Maintenance repo

## Additional context
* It would be interesting to see metrics like this example from the article
<img width="738" alt="Screenshot 2023-10-11 at 12 31 10 AM" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/0192a7ce-5562-4046-9c8f-9561c9e1823e">

**Comment by sirish123** [comment]
Could u assign this to me!

**Comment by mikaelacaron** [comment]
Go for it! Let me know if you need anything from me, to be able to read my repo, but you might be able to make a prototype on your own fork

**Comment by mikaelacaron** [comment]
Thank you for wanting to contribute!

I'm going to un-assigning you from this issue because it hasn't been updated in 3 weeks days, and there's only 2 days left in Hacktoberfest, and I want to allow others to be able to contribute to the project

**Comment by anupdsouza** [comment]
Hey @mikaelacaron, I'd like to take a look into this.

**Comment by mikaelacaron** [comment]
@anupdsouza Go for it! Thanks!

**Comment by mikaelacaron** [comment]
Attempted to run, but failed, details:
https://github.com/mikaelacaron/Basic-Car-Maintenance/actions/runs/10089980810/job/27898454351


PR #278 is when this code was merged in, but didn't work on the first run

**Comment by mikaelacaron** [comment]
I've figure it out over several commits how to make a single report for issues / PRs that are opened, and then another report for issues / PRs that are closed, because their action doesn't support the "and" operator to be able to combine everything yet
