### ISSUE TITLE
FEATURE - Firebase Analytics Add / Update / Delete

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#139]
## Describe the feature you want the app to have that it currently doesn't
* Log [Firebase Analytic](https://firebase.google.com/docs/analytics/events?platform=ios) events. Do not log *what* the user wrote, but that the action happened successfully
   * Create a new vehicle
   * Update a vehicle
   * Delete a vehicle
   * Create a maintenance event
   * Update a maintenance event
   * Delete a maintenance event

## Describe alternatives you've considered
* N/A

## Additional context
* Feel free to DM @mikaelacaron on social media and ask if I see any new events come in from your testing (at the moment, I am not adding anyone to the Firebase project), so the only way to check if it worked is by Mikaela viewing the console, or by adding more logging in Xcode, as shown in the post linked above

**Comment by narendrajagne** [comment]
Hii can you assign me this ?

**Comment by mikaelacaron** [comment]
@narendrajagne You've done #33, I labeled this issue `first-timers-only`, so only someone new to contributing to this project should pick up this one! Thanks!

**Comment by 0xJsaad** [comment]
Hey! I would love to work on this as a first timer

**Comment by peterfriese** [comment]
You can use the `analyticsScreen` view modifier to implement this: https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAnalyticsSwift/Sources/Analytics%2BSwiftUI.swift#L56

**Comment by mikaelacaron** [comment]
> You can use the `analyticsScreen` view modifier to implement this: https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAnalyticsSwift/Sources/Analytics%2BSwiftUI.swift#L56

@peterfriese That's for logging which screen, right, not a specific event from a button action?

**Comment by peterfriese** [comment]
> > You can use the `analyticsScreen` view modifier to implement this: https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAnalyticsSwift/Sources/Analytics%2BSwiftUI.swift#L56
> 
> 
> 
> @peterfriese That's for logging which screen, right, not a specific event from a button action?

That's right. Sorry for mixing up screens (which you can definitely track with this modifier) and actions.

That being said, if you come up with a reusable way to encapsulate an action, this might even be worth considering a contribution to the Firebase SDK.
