### ISSUE TITLE
Setup the Firebase Local Emulator 

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#14]
## Details
* Following [this tutorial](https://peterfriese.github.io/MakeItSo/tutorials/makeitso/02-developing-locally-with-the-emulator-suite), set up the project to use the Firebase local emulator when developing and use real Firebase for production
* Update the README.md and CONTRIBUTING.md with instructions about how to use the Firebase local emulator, if needed (if you're not sure what to say for set up, comment in the PR and Mikaela can update it)

## Describe alternatives you've considered
* N/A

## Additional context
* N/A

**Comment by nnethaji** [comment]
@mikaelacaron Can I work on this? Thanks

**Comment by n0rthk1n9** [comment]
@mikaelacaron I would like to take this please :)

**Comment by yashlangaliya** [comment]
@mikaelacaron I would like to work on this if its still available :)

**Comment by n0rthk1n9** [comment]
@yashlangaliya I DM'd @mikaelacaron that I'm still working on it. I'll reach out, if I need help :)

**Comment by mikaelacaron** [comment]
Fixed with #299 
Thanks @n0rthk1n9 for all your work on this!
