### ISSUE TITLE
IMPROVE - Remove `Gravatar` from the `Contributor` model

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#140]
## Describe the feature you want to improve
* There's no need to fetch `gravatarID` because it's not used and has been deprecated since 2014
* Remove it from the model

## Describe alternatives you've considered
* N/A

**Comment by AakifNadeem** [comment]
@mikaelacaron I've completed the title renaming issue can you kindly assign it to me.

**Comment by mikaelacaron** [comment]
You did #149, this one is labeled `first-timers-only` so it's only for people new to the repo, can you find a different issue to work on? Thanks!

**Comment by SarathVSasikala** [comment]
Hi @mikaelacaron, I like to work on this issue, can you assign it to me?
