### ISSUE TITLE
FEATURE - Connect `Vehicle`s and `MaintenanceEvent`s

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#141]
## Describe the feature you want the app to have that it currently doesn't
* The `Vehicle` object needs to correspond to a `MaintenanceEvent`
* When creating a new `MaintenanceEvent` a new row needs to be added so that a user can select which `Vehicle` this event belongs to.
* I want to make a [menu like this](https://www.hackingwithswift.com/quick-start/swiftui/how-to-let-users-pick-options-from-a-menu)

## Describe alternatives you've considered
* There's many ways to implement this, at the moment the easiest is probably just fetching the vehicles inside of the `AddMaintenanceView`, in a function. Because otherwise it would require rewriting too much of the app at this point

## Additional context
* Also update the `EditEventDetailView` with the new property
* Once this is done, the widget tasks can be started (which are all separate for each widget size)

**Comment by hanhqvu** [comment]
@mikaelacaron I would like to handle this.

**Comment by hanhqvu** [comment]
@mikaelacaron I just would like to confirm my understanding on how to proceed:
- I checked the `AddVehicleView` under `Settings` the Add method is not yet implemented.
Should I declare a temp method to fetch all `Vehicles` but use mock data to show the menu for now?
- I assume the vehicles would be fetch from Firebase using the bundle SDK but please correct me if I'm wrong.
- Is it okay for me to add unit & UI tests for this view?

**Comment by mikaelacaron** [comment]
> I checked the AddVehicleView under Settings the Add method is not yet implemented.
Should I declare a temp method to fetch all Vehicles but use mock data to show the menu for now?

This is implemented the `addTapped` closure is called and implemented in the `SettingsViewModel` for actually calling to Firebase


> I assume the vehicles would be fetch from Firebase using the bundle SDK but please correct me if I'm wrong.

Correct

> Is it okay for me to add unit & UI tests for this view?
Go for it!

Thank you for checking with me!
