### ISSUE TITLE
FEATURE - Large Content Viewer

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#142]
## Describe the feature you want the app to have that it currently doesn't
* Make the large content viewer use the label and image for the plus button and filter button on the `DashboardView`

## Describe alternatives you've considered
* N/A

## Additional context
* More details here about the [Large content viewer](https://nilcoalescing.com/blog/LargeContentViewerInSwiftUI/)

**Comment by ghost** [comment]
Hello there!
could you please assign me this task.

**Comment by ghost** [comment]
@mikaelacaron please assign this task to someone else!

**Comment by mikaelacaron** [comment]
@swaleha2002 Okay, ps in GitHub you can unassign yourself to tasks

**Comment by hanhqvu** [comment]
@mikaelacaron It seems there is no one working on this so I would like to take it!

**Comment by mikaelacaron** [comment]
@hanhqvu You got it! 👍

**Comment by mikaelacaron** [comment]
Wait actually @hanhqvu I'm going to assign this to someone else because I labeled this one `first-timers-only`, so it's only for people who are new to the project

**Comment by hanhqvu** [comment]
@mikaelacaron Ah, sorry I missed the label. No worries!

**Comment by mikaelacaron** [comment]
Thanks for understanding!

**Comment by ilyapaddubny** [comment]
Then I can take it.
