### ISSUE TITLE
FEATURE - Search `MaintenanceEvent`s on the `DashboardView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#143]
## Describe the feature you want the app to have that it currently doesn't
* Add a search bar to be able to search through the titles of the maintenance events on the `DashboardView`

## Describe alternatives you've considered
* N/A

## Additional context
* N/A

**Comment by sergpryimachuk** [comment]
Hey @mikaelacaron, I can take this one 🙋‍♂️

**Comment by mikaelacaron** [comment]
Closed with #150
