### ISSUE TITLE
IMPROVE - Switch the order of the toolbar items

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#144]
## Describe the feature you want to improve
* Change the order of the plus an filter toolbar items, so that the plus is on the outside and the filter, is to the left of it

## Describe alternatives you've considered
* N/A

## Screenshot
* Current view
<img width="339" alt="Screenshot 2023-10-11 at 1 35 53 AM" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/1723c088-4329-4f5a-8684-010b1a1a88a0">

**Comment by AakifNadeem** [comment]
@mikaelacaron can you kindly assign it to me.

**Comment by majeedyaseen** [comment]
@mikaelacaron can I work on this ?

**Comment by mikaelacaron** [comment]
@AakifNadeem You did #149, I labeled this issue `first-timers-only` so it's only people new to the repo! Can you find another issue to work on, thanks!
@majeedyaseen you got it!

**Comment by PrashannaR** [comment]
can i work on this @mikaelacaron?

**Comment by mikaelacaron** [comment]
@PrashannaR  I've assigned this to @majeedyaseen already! You can look for another issue, if there aren't any, you create one, but I add new ones throughout the month

**Comment by PrashannaR** [comment]
oh, alright. I'll have a look. Thanks :)

**Comment by mikaelacaron** [comment]
Are you planning on updating this in the next few days? Hacktoberfest ends in about 1 week, for it to count as a PR, it needs to be merged or accepted by the 31st.

If you're not interested in updating this let me know, or remove yourself as an assignee on the issue, thank you!

**Comment by majeedyaseen** [comment]
I am raising the PR in sometime @mikaelacaron

**Comment by mikaelacaron** [comment]
Great thank you! Sorry tagged the wrong person, reading the comments wrong
