### ISSUE TITLE
FEATURE - Firebase Security Rules

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#146]
## Describe the feature you want the app to have that it currently doesn't
* What should be the Firebase Firestore security rules?
* This is the current schema:
   * `alerts`, anyone can read
   * `maintenance_events` collection
      * `documentID`, then properties
      * includes a `userID`, so you can only read your own events you created
   * `vehicles`
      * `documentID`, then properties
      * includes a `userID`, so you can only read your own events you created

## Describe alternatives you've considered
* N/A

## Additional context
* This is for Firebase Firestore, add the code to what these rules should be in the Documentation.md, or create a new file and link to it in the documentation, so you're documenting what the security rules are, so that people new to the project understand
   * Also describing what each collection is would be helpful too

**Comment by Kundai10** [comment]
May you please assign this issue to me. I want to work on it

**Comment by Kundai10** [comment]
@mikaelacaron  I am so sorry. Unfortunately I cannot work on this as this seems to be an iOS project. I use windows. Again, I am so sorry for any inconveniences this might have caused.

**Comment by mikaelacaron** [comment]
@Kundai10 Technically this specific issue, you can write the rules in the DocC documentation file, which is a markdown file, but you just won't be able to compile anything.

But if you aren't interested, please unassign yourself, thank you for trying!

**Comment by Kundai10** [comment]
@mikaelacaron I am interested. Let me try, and I will keep you updated after every 2 days. May I please have more context about the problem I am trying to solve? I can't find the documentation.md file, or should I create one myself? I am new to open source, so I apologise for the many questions. And thank you for assigning the issue to me.

**Comment by mikaelacaron** [comment]
I think if you're brand new it may be best to work on a project where you can actually build and test the code. That is not possible for you with this project because it is for iOS development, and requires a Mac. Also if you do not understand iOS development and Swift, this will be extremely difficult for you to understand.

**Comment by Kundai10** [comment]
@mikaelacaron Okay, I understand. Feel free to assign the issue to someone else. And thanks!

**Comment by mikaelacaron** [comment]
Thank you for trying!

**Comment by rramirez-dev** [comment]
What is the purpose of the alerts collection?

**Comment by mikaelacaron** [comment]
> What is the purpose of the alerts collection?

See #107

**Comment by rramirez-dev** [comment]
Can you assign this to me?
