### ISSUE TITLE
FEATURE - Start `OdometerView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#152]
## Describe the feature you want the app to have that it currently doesn't
* Create a view similar to the `DashboardView` and `AddMaintenanceEventView` for adding new odometer readings
* Be able to select a `Vehicle` for the user that this new entry will belong to
* Save to Firestore (in a similar way that the `MaintenanceEvent` and `Vehicle` is formatted, it should be in a collection called `odometer_readings`

## Describe alternatives you've considered
* N/A

## Additional context
* Only do "create" and "read" the update will be a separate issue
* Create:
   * `AddOdometerReadingView`
   * `struct OdometerReading` for the model
* Be able to handle entering miles or kilometers

**Comment by mikaelacaron** [comment]
@thx1766 you mentioned you wanted to work on this. Comment below and I can assign it to you

**Comment by thx1766** [comment]
I would indeed like to work on this! Thanks @mikaelacaron !

**Comment by mikaelacaron** [comment]
Use basic controls and make it simple! like the rest of the app, we can always optimize and make it prettier later! Thanks! @thx1766
