### ISSUE TITLE
BUG - Firebase Warning

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#159]
## Describe the bug
* When you add a new `Vehicle` or `MaintenanceEvent` a warning like this is shown in the console.
* We are fetching an array of items returned from Firebase, when a new item is added, it doesn't have a document ID because it's assigned by Firebase. This creates an issue when going to delete an item immediately after it's created. See #134 the solution to this is setting the document ID manually

* But that solution, leads to this output, that Firebase doesn't want us to do this.

```
Attempting to initialize or set a @DocumentID property with a non-nil value: "ugfj380dZQf0rubpWjAL". The document ID is managed by Firestore and any initialized or set value will be ignored. The ID is automatically set when reading from Firestore.
```

### Possible Solution
One way to solve this is going back and fetching the new items to refresh the local array (and removing the statements explicitly setting the document ID

## To Reproduce
1. Go to `DashboardView`
2. Tap the `+` button
3. Fill in the text fields and tap Add
4. See the console output like above

## Expected behavior
* This output is not shown in the console
* You can create new items (`MaintenanceEvent` or `Vehicle`) and delete them right after they're created

## Screenshots
* N/A

## Device Info (please complete the following information):
 * Device: any iPhone
 * OS: iOS 17
 * App Version: v1.0 (1)

## Additional Context
* N/A

**Comment by SarathVSasikala** [comment]
Hi @mikaelacaron , I like to wok on this issue. can you assign it to my name?

**Comment by SarathVSasikala** [comment]
@mikaelacaron  thanks for assigning this issue to my name. 

I suggest adding a new func in DashboardViewModel.
```
    func syncEvents() {
        Task {
            await self.getMaintenanceEvents()
        }
    }
```
and we can sync with Firebase during Add 

```
        AddMaintenanceView { event in
            viewModel.addEvent(event)
            viewModel.syncEvents()
        }
```
Could you please share your insights on this?

**Comment by mikaelacaron** [comment]
Yes that's what I suggested above, and is one way to solve this

**Comment by mikaelacaron** [comment]
@SarathVSasikala Can you actually please finish this issue, I merged it because I wasn't looking closely enough, but this needed to be fixed for both maintenance events and vehicles. You only fixed the maintenance events

**Comment by SarathVSasikala** [comment]
@mikaelacaron I initially assumed someone else was handling this issue since I noticed other vehicle-related issues being addressed. However, I have now implemented the same logic for vehicles. Could you please review the PR? Your feedback is appreciated, and I'm here to assist in any way 😁.
