### ISSUE TITLE
FEATURE - View GitHub Contributors

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#16]
## Describe the feature you want the app to have that it currently doesn't
* Create a new section in the `SettingsView` called "Contributions" to view the list of contributors to the app, using the GitHub API (no login required)
* See how it was implemented [here](https://github.com/mikaelacaron/brain-marks/blob/025cbbb20df75c958df426bb63866cfce757b5e1/brain-marks/Settings/SettingsViewModel.swift#L13), in one of my archived repos

## Describe alternatives you've considered
* N/A

## Additional context
* Load the usernames and avatars

**Comment by Yashraj49** [comment]
Hello , @mikaelacaron I like to take this issue .  please assign me this one

**Comment by vagxrth** [comment]
Hey, @mikaelacaron I would love to work on this issue. Can you please assign it to me?
