### ISSUE TITLE
FEATURE - Add Properties to `Vehicle`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#166]
## Describe the feature you want the app to have that it currently doesn't
* Add these properties to the `Vehicle` model, they are all strings
   * `year`
   * `color`
   * `VIN`
   * `licensePlateNumber`

## Describe alternatives you've considered
* N/A

## Additional context
* You will need to update the `AddVehicleView` and the `SettingsView` where the vehicles are listed
* You can't update vehicles yet because that is part of #5

**Comment by DarkSoul26** [comment]
@mikaelacaron can you assign this to me?
