### ISSUE TITLE
FEATURE - Alternative App Icons

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#17]
## Design
* Design one or two alternative app icons, size them 1024 x 1024, with no corner radius (that happens automatically)

## Describe alternatives you've considered
* Comment if you want to implement the design in code, (and Mikaela will create a new issue), this issue is only for the design
* I'm also open to a complete redesign, if you want!

## Additional context
* N/A

**Comment by DandyLyons** [comment]
I would like to implement alternative app icons in code. I'm open to doing design work, but only if you'd permit using AI tools like Midjourney. (I'd rather do do the code than the design though).

**Comment by mikaelacaron** [comment]
Right now I'd want an actual person to do the design, I can ping you @DandyLyons after someone picks up the design work!

**Comment by clydehenry3** [comment]
Hi there! I am in boot camp for UX Design and would love to see if I could take this on. I am a super beginner to OSS but not to design. Happy to help.

**Comment by mikaelacaron** [comment]
@clydehenry3 Yes go for it! the current app icon is in the project, but I am open to any design!

**Comment by clydehenry3** [comment]
Great, I will get right on this!

**Comment by mikaelacaron** [comment]
@clydehenry3  The recommended size is 1024 x 1024, if you can make 2 alternatives, that'd be great! But otherwise if you want to make anymore, go ahead, but not required. Also we can DM on Discord, but there's several other UI / UX things I'd love to get into

**Comment by clydehenry3** [comment]
@mikaelacaron I am super excited to get these together. I planned to give you a couple of options because people love options. I would love to dive into other UX & UI things. User flows, screens, experience, mobile, desktop, etc. I am your guy!

**Comment by mikaelacaron** [comment]
@clydehenry3 Awesome!! Let's chat via Discord, I have some ideas, but also after I merge all the PRs today, haha some stuff will definitely change, can you also DM me the app icons whenever you finish them (cause I'm not sure if Discord messes up the format

But I'll also have you make a PR and drop the app icons there too (even though I know no code has changed, I think this is a requirement of hacktoberfest, but I'll double check)

**Comment by mikaelacaron** [comment]
@DandyLyons the icons are up! they should be on the `dev` branch. I have not changed anything else
[This article](https://www.avanderlee.com/swift/alternate-app-icon-configuration-in-xcode/) may be helpful
* AppIcon-car-red
* AppIcon-car-yellow
* AppIcon-car-black
* AppIcon-car-orange
* AppIcon-car-dark
