### ISSUE TITLE
BUG - Fastlane Unit Tests

### ISSUE THREAD

**Issue by hanhqvu** [mikaelacaron/Basic-Car-Maintenance#173]
## Describe the bug
* Currently the Unit tests lane for `Fastlane` is not running, all tests appear as passed even if some failed

## To Reproduce
1. Write a test that failed under `Basic-Car-Maintenance-Tests`
2. Run the command `bundle exec fastlane unit_tests`
3. The results in the command line doesn't show any failed test.

![](https://user-images.githubusercontent.com/82783173/273749869-cb605dba-db00-417c-bb98-0428908ccd47.png)

## Expected behavior
If there's a failed test, the command line results should look like below:
![](https://user-images.githubusercontent.com/82783173/274957123-635d73d2-3b95-4e1c-b69d-fd3c8cb94d05.png)

## Screenshots
Refer to the screenshot above

## Device Info (please complete the following information):
N/A

## Additional Context
* This is tied to the Github Action to run unit tests on PR to `dev` branch

**Comment by Ditosabrii** [comment]
i am willing try to fix this bug .

**Comment by mikaelacaron** [comment]
Great!! Thanks @Ditosabrii

**Comment by anupdsouza** [comment]
Hey @Ditosabrii, are you working on this? If not I can take it off your hands as I've fixed it in my copy already.

**Comment by anupdsouza** [comment]
Hey @mikaelacaron , can I pick this up? I have this working in my fork after I noticed the issue in #123

**Comment by mikaelacaron** [comment]
@anupdsouza Yes! Because @Ditosabrii hasn't responded
