### ISSUE TITLE
IMPROVE - Update the design of `MaitenanceEvent` list element in `DashboardView`

### ISSUE THREAD

**Issue by hanhqvu** [mikaelacaron/Basic-Car-Maintenance#174]
## Describe the feature you want to improve
* Currently the list element for `MaintenanceEvent` the `DashboardView` is getting a bit crowded,
so please update the design like below.
* The placement are as follow:
`Event Tittle` 
`Vehicle Name` + on + `Event Date`
`Event Notes`

![image](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/82783173/ad7a21e6-3c75-4daa-85a5-83b39b0c109b)

## Notes
* Please ignore the font/size/weight and just focus on the placement of the text.
* Please do not hard code the date but format it according to locale, languages etc using the `.formatted` API
* You can refer to [Apple document](https://developer.apple.com/documentation/xcode/preparing-dates-numbers-with-formatters/) or [this blog post](https://sarunw.com/posts/new-formatters-in-ios15/) that goes into detail.

## Describe alternatives you've considered
* We discussed making this collapsible but decided on the design☝️

**Comment by mikaelacaron** [comment]
I don't think collapsing is the right solution here. I think either a redesign to make it look better, or only show some info and then tapping on the row to see a detail view would be a better solution

**Comment by hanhqvu** [comment]
In that case, let me find a good example for a design for this.
Since we have the `Edit`, maybe we can turn that into a detail view with an edit mode?

**Comment by mikaelacaron** [comment]
Yes that sounds good!

It could be a view / edit, so out would have two "modes"

**Comment by hanhqvu** [comment]
@mikaelacaron I think something like this could work for the `DashboardView`
![image](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/82783173/204bc705-2193-46ca-b535-62f8f0d28db7)
Then implement something like [Edit Mode](https://developer.apple.com/documentation/swiftui/editmode) for the `DetailView`

**Comment by mikaelacaron** [comment]
I'm good with this change, (it looks like you changed the font, was that intentional?)
Also I'd prefer the date to be the shorter date like `10-16-23` (or whatever it is properly localized)

The edit mode, let's hold off for right now, you can create the issue, but I don't want to implement it just yet (the dashboard view will likely change), and won't always only be a list

**Comment by hanhqvu** [comment]
Sorry about the font, I just grabbed a default from Figma.
I'll check to see how we can shorten the date.
I hold off on the edit mode for now as well.

**Comment by mikaelacaron** [comment]
No problem, I just wanted to make sure you meant a default font, and not adding a new font.
If you can make a quick update to your original sketch that would be great, comment here if you want to take this otherwise, I think this is a `first-timers-only` issue, which would be for beginners and someone who hasn't contributed to this prjoect yet

**Comment by hanhqvu** [comment]
I have updated the info accordingly, please feel free to assign this to anyone who fits `first-timers-only`

**Comment by mitaligondaliya** [comment]
Hello,
I am first time user to start working on this project, I want to work on this issue, Can you please assign me?

**Comment by mikaelacaron** [comment]
@mitaligondaliya You got it!

**Comment by mitaligondaliya** [comment]
@mikaelacaron There should be shadow and border applied on view or it is fine with the date format and text placement changes?

**Comment by mikaelacaron** [comment]
@mitaligondaliya I'd prefer a border over a shadow for accessibility, but do whichever you think looks best (or you can also screenshot both and drop those here and I can take a look)

**Comment by mitaligondaliya** [comment]
Okay @mikaelacaron  I'll check and let you know

**Comment by mitaligondaliya** [comment]
![Simulator Screenshot - iPhone 15 Plus - 2023-10-18 at 11 26 36](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/29226517/d7ea1e3d-fbb0-43db-a4ad-aa91ba3b4a09)
![Simulator Screenshot - iPhone 15 Plus - 2023-10-18 at 11 26 31](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/29226517/5dac1134-b564-468d-9f64-9a6d5cb9f25f)
![Simulator Screenshot - iPhone 15 Plus - 2023-10-18 at 09 14 49](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/29226517/fee8249c-18bb-4344-b471-d8c17c2307f5)

@mikaelacaron The default list style we've already as current looks nice for me, Shadow I've added you can compare with current design, one thing using custom design needs to handle the swipe action design also. Let me know whichever you feel to add I'll do changes accordingly.

**Comment by mikaelacaron** [comment]
@mitaligondaliya definitely the default
