### ISSUE TITLE
FEATURE - User Bugs / Feature Requests from `SettingsView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#18]
## Describe the feature you want the app to have that it currently doesn't
* Create a new row under the GitHub Repo row in the 1st section of `SettingsView` called "Request a New Feature" that links the user to create a new feature in the GitHub repo
   * Choose any SF symbol that fits for this "request a new feature" row
   * Link to here:`https://github.com/mikaelacaron/Basic-Car-Maintenance/issues/new?assignees=&labels=feature+request&projects=&template=feature-request.md&title=FEATURE+-`
* Create a new for row for "Report a Bug"
   * Use the `ladybug` SF symbol
   * Link here: `https://github.com/mikaelacaron/Basic-Car-Maintenance/issues/new?assignees=&labels=bug&projects=&template=bug-report.md&title=BUG+-`

## Describe alternatives you've considered
* Yes this requires someone to have a GitHub account to actually find this useful, but that's fine for now

## Additional context
* Add any other context or screenshots about the feature request here.

**Comment by mishapark** [comment]
Hi, please assign this issue to me

**Comment by mikaelacaron** [comment]
> Hi, please assign this issue to me

@mishapark you can only work on **ONE** issue at a time, please go through and delete your comments on all the other issues, you commented on already. Do NOT start working on this until Oct 1, because the code base isn't ready yet

**Comment by mishapark** [comment]
Got it, thanks for letting me know

**Comment by mikaelacaron** [comment]
Closed with #21
