### ISSUE TITLE
BUG - Picker in AddMaintenanceView is not working

### ISSUE THREAD

**Issue by Drag0ndust** [mikaelacaron/Basic-Car-Maintenance#182]
## Describe the bug
It is not possible to select another vehicle in the AddMaintenanceView.

## To Reproduce
1. Add more than on vehicle in the settings screen
2. Add a new maintenance
3. Try to select the second vehicle in the picker

## Additional Context
* Problem is that the picker selection should only use id not the vehicle object.

@mikaelacaron  I already have a working bugfix, but I wanted to give someone else the chance to fix it. If the solution is needed immediately I can open a PR with the fix.

**Comment by mikaelacaron** [comment]
@Drag0ndust This was fixed, you saw this on `dev` with the latest changes?

**Comment by Drag0ndust** [comment]
yeah, dev from around one hour ago

**Comment by mikaelacaron** [comment]
I'll double check this later! 👍 thanks for making the bug report!

**Comment by rramirez-dev** [comment]
Can you assign this to me?
