### ISSUE TITLE
IMPROVE - Display a Launch Screen

### ISSUE THREAD

**Issue by rramirez-dev** [mikaelacaron/Basic-Car-Maintenance#191]
## Describe the feature you want to improve
Display a splash screen with the app logo and title when the app loads.

## Describe alternatives you've considered
You could also just display the app logo.

**Comment by mikaelacaron** [comment]
What do you mean by "splash screen?" the launch screen? or like onboarding?

**Comment by mitaligondaliya** [comment]
@mikaelacaron @rramirez-dev  I would like to work on this, Can you please assign it to me?

**Comment by mikaelacaron** [comment]
@mitaligondaliya I don't think this issue is ready to be worked on yet, without clarification from @rramirez-dev about what he was envisioning. Once it's finalized, @rramirez-dev has first grabs on if he wants to implement it, because he created the issue, otherwise, you're next in line

**Comment by rramirez-dev** [comment]
I do mean "launch screen". Do you want me to change the title to launch screen?

**Comment by mikaelacaron** [comment]
Yes also please fill out the template properly and do not delete anything from it. I've dropped it here, please add these titles back to your original issue description.

Do you want to work on this issue?

```md
## Describe the feature you want to improve


## Describe alternatives you've considered

```

**Comment by rramirez-dev** [comment]
You can assign it to someone else.

**Comment by mikaelacaron** [comment]
@mitaligondaliya it's all yours! Be sure to display the correct app icon that the user has chosen, because they can change it

**Comment by mitaligondaliya** [comment]
@mikaelacaron You want to show a launch screen at the time of launching app that will for 1 or 2 sec and after that main view will show. Am I correct here?

**Comment by mikaelacaron** [comment]
Yes this is default behavior. I think you need to use the `Launchscreen.storyboard`, I can't remember if this can use a SwiftUI view

**Comment by rramirez-dev** [comment]
Maybe we should display the launch screen until the dashboard is loaded and indicate that the dashboard is loading.

**Comment by mikaelacaron** [comment]
Technically that would be best. A launch screen is supposed to indicate that your app is quick to launch, and in reality, just showing the app icon, doesn't really mean anything. That's why apps like Facebook and Instagram show that "shimmer" loading UI, because it's like a blank "skeleton" of the app loading and makes it look faster than just a spinner.

See the [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/launching) about launch screens.

Technically just an app icon isn't the best experience, but I'm fine with it. "Waiting for the dashboard to load" would mean you would need to know when the data is done loading, in the launch screen part, which is more difficult, than just showing a screen, and using the default timing / animation from the launch screen to the first screen of the app

**Comment by mitaligondaliya** [comment]
@mikaelacaron So, you concluded to show a launch screen with icon and default timer to replace the main screen?

**Comment by mikaelacaron** [comment]
Yes just the icon is fine, make sure to use the right one based on what the user's selected from settings.
And don't create a new timer, but yeah just use the default launch screen settings

**Comment by mitaligondaliya** [comment]
@mikaelacaron Default launch screen doesn't allow to update the image dynamically, we can either create the custom launch screen. I mean first we need to fetch the selected app icon that will not allow in default launch screen there we can add static image only.

**Comment by mikaelacaron** [comment]
The `ChooseAppIconViewModel.swift` uses the init to figure out which icon is selected, is it possible to use that to get which icon to use when setting the picture?

**Comment by mitaligondaliya** [comment]
Yeah but for that we need file to fetch the current selected icon which in case of default launch screen only have the storyboard and we can add icon inside the storyboard, UIKit has that functionality to create the view controller class of default launch screen and customisations. Need to check if SwitUI is allowing to do that but again that will be UIKit class we've to handle here for default launch screen.

**Comment by mikaelacaron** [comment]
I think it's fine just to use UIKit for the Launch screen

**Comment by mitaligondaliya** [comment]
I tried adding launch screen UIKit class which says `Launch screens may not set custom classnames'

Note that the launch screen is is not a fully customizable view controller. You cannot specify a custom class name in the storyboard and expect the system to give you the option to execute code at this stage by calling viewDidLoad. Remember, the app hasn’t launched yet.

**Comment by mikaelacaron** [comment]
@mitaligondaliya 
Thanks for wanting to contribute! Hacktoberfest ended on October 31, if you can still finish this issue by Saturday November 4, I’ll accept it, but otherwise after that I’ll be un-assigning all issues and cleaning up the code to ship this app to the App Store

**Comment by mitaligondaliya** [comment]
@mikaelacaron As you said to use UIKit launch screen will not allow for dynamic app icon, we can create the custom launch screen and view for that Should I go ahead with it?

**Comment by mikaelacaron** [comment]
If you can finish this by Friday Nov 4, go ahead, if not, don't worry about it

**Comment by TratonGossink** [comment]
@mikaelacaron is this still available?
If so, what style did you want? I'd suggest a default display of the app name with just text and/or a defualt icon. The launch screen is possible with SwiftUI.

**Comment by mikaelacaron** [comment]
After chatting @TratonGossink I'm going to close this issue for now! I don't think this app needs a launch screen
