### ISSUE TITLE
IMPROVE - Analytics Screen View Modifier

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#197]
## Describe the feature you want to improve
* Right now there are 8 views that have this modifier`.analyticsScreen(name: "\(Self.self)")` on them
* Create a new file called `FirebaseAnalytics+Extension` with a new view modifier that uses this modifier (put this file in the `Utilities` folder)
   * The new modifier should be called `analyticsView`
* Go through and use the newly created modifier on each view and remove the `import FirebaseAnalyticsSwift` on all the views, where necessary

The goal is that the new view modifier file has only a single import, and that we no longer need to import `FirebaseAnalyticsSwift` on all the views 

## Describe alternatives you've considered
* N/A

**Comment by am2089** [comment]
Can I tackle this?

**Comment by mikaelacaron** [comment]
I labeled this `first-timers-only` so it's only for someone who's brand new to the repo and hasn't contributed yet!

**Comment by am2089** [comment]
Ohhh lol gotcha.

**Comment by vishnukaushik** [comment]
@mikaelacaron Can I work on this?

**Comment by mikaelacaron** [comment]
This was livestreamed on my YouTube channel, as an example, but this issue is still open!

In the stream I do go through how this issue should be completed, and the basics of git and GitHub

https://www.youtube.com/live/-rYYKXrCyro?si=r9D0ii3D1T7OLhlM

**Comment by vishnukaushik** [comment]
@mikaelacaron could you please assign this to me?

**Comment by jessielinden** [comment]
Hi! I am an open source first-timer, but not new to git so not sure if this is a good one for me but if you feel it is I'd love to have a go!

**Comment by mikaelacaron** [comment]
@jessielinden it is up to you!! You can do it! See my livestream linked in one of the comments, I did most of the task itself as an example
