### ISSUE TITLE
DocC Naming

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#198]
Does anyone know, why the DocC documentation shows as underscores for the name`Basic_Car_Maintenance`?

Is it possible to change it to `Basic-Car-Maintenance` or just `BasicCarMaintenance`?

Would the script `build-docc.sh` need to be updated if this can be changed?

<img width="338" alt="Screenshot 2023-10-21 at 1 41 34 AM" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/b9da2bb4-a8de-41e2-aa48-852cc3df624e">

**Comment by hanhqvu** [comment]
@mikaelacaron I would like to take this issue!

**Comment by hanhqvu** [comment]
FYI, DocC will take the `Product Module Name` to use as title. Hyphen is not allowed but CamelCase is okay.
There is no build settings transformation to remove hyphen so I set the value manually.

**Comment by mikaelacaron** [comment]
Closing because it will be closed with #207
