### ISSUE TITLE
Social Preview Image for the Repo

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#2]
## Description
* Create a social preview image used for the repo (Mikaela will upload this, and it'll be the preview image when the link to the repo is shared
* This can be an image using Hacktoberfest's official fonts and colors for this year
* 1280×640px

## Describe alternatives you've considered
* N/A

## Additional context
* The image should have the repo name, some fun graphics that are Hacktoberfest themed and convey that this is an open source project for iOS developers of any experience level to contribute to!
* Somewhere include my name `Mikaela Caron` as the maintainer

**Comment by sarafurd** [comment]
Please assign this to me

**Comment by mikaelacaron** [comment]
> Please assign this to me

Hi @sarafurd  we haven't started Hacktoberfest yet, so I'm not yet assigning issues, but I will starting October 1st!

**Comment by chloebeau** [comment]
Would be happy to work on this @sarafurd

**Comment by mikaelacaron** [comment]
> Would be happy to work on this @sarafurd 

@chloebeau it'll be one person per issue!

**Comment by sarafurd** [comment]
I've tried to work on your issue, and I realized that it's something that a designer should do. I'm unassigning myself from the issue so that someone else can pick it up. Sorry for any inconvenience.

**Comment by mikaelacaron** [comment]
No problem! It doesn't have to be fancy at all, using Hacktoberfest's colors and fonts from the website would be totally fine

@chloebeau do you want to take this issue?

**Comment by chloebeau** [comment]
Yes thank you!

**Comment by mikaelacaron** [comment]
@chloebeau any progress on this?

**Comment by mikaelacaron** [comment]
Un-assigning because there's been no progress in 2 weeks

**Comment by rramirez-dev** [comment]
I've been trying some ideas. What do you think?
![Hacktoberfeset23](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22773854/77458d00-1082-4a76-adb1-487e6837961e)

**Comment by mikaelacaron** [comment]
Love that!! Can you add my unicorn emoji after my username?

**Comment by rramirez-dev** [comment]
Ok. I had it there initially but I removed it because it didn't match the color scheme. Can you assign this to me. Here is  the new version.
![Hacktoberfeset23](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22773854/0cfbe9fa-2826-4956-ac8c-9f615eb32cbd)

**Comment by mikaelacaron** [comment]
For this can you just use the emoji, rather than the profile pic?

**Comment by rramirez-dev** [comment]
Here is the final version with your emoji and some grammar fixes
![Hacktoberfeset23](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22773854/a08bce38-1c04-49ef-afa5-1b7dcceefb85)

**Comment by mikaelacaron** [comment]
@rramirez-dev one tiny change, can you add a space after my name and the emoji
Also did you make this in Figma? If so DM me your email and I can add you to the official Figma board, and you could copy this there, so that I have the original file too, thank you!

And this can count as a Hacktoberfest PR!! Create a PR, and add this as a banner image to the DocC documentation!

**Comment by rramirez-dev** [comment]
Here is the updated image. I will also create a pull request
![Hacktoberfeset23](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22773854/bc7f86ca-62b3-4384-95ad-19fb2215e038)
.

**Comment by mikaelacaron** [comment]
Closed with #240
