### ISSUE TITLE
Prevent Users From Deleting All Vehicles

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#202]
## Describe the feature you want the app to have that it currently doesn't
* The user shouldn't be able to delete all of their vehicles
* When they swipe to delete, once they're attempting to delete the last one, show an alert
   * **Title**: `Can't Delete Last Vehicle`
   * **Message**: `The last vehicle can't be deleted`

## Describe alternatives you've considered
* N/A

## Additional context
* N/A

**Comment by chrisjniles** [comment]
Hello! I would like to work on this issue, please.

**Comment by rramirez-dev** [comment]
Since the app starts with no vehicles the user should be prevented from adding an event if there are no vehicles available.

**Comment by mikaelacaron** [comment]
> Since the app starts with no vehicles the user should be prevented from add an event if there are no vehicles available.

Do NOT put that in this scope. @rramirez-dev This should be a separate issue

**Comment by rramirez-dev** [comment]
Why are we preventing the user from deleting all their vehicles?

**Comment by mikaelacaron** [comment]
@rramirez-dev right now if you attempt to add a maintenance event and you haven't added a vehicle, it shows a field as "select vehicle" but that's only text. It's not a picker, but there's no vehicle to select because they're all gone


Preventing a user from deleting all vehicles makes it so they never see that view

**Comment by rramirez-dev** [comment]
But you will still see text when you launch the app for the first time and you have no vehicles. So this change doesn't solve the issue. Correct

**Comment by mikaelacaron** [comment]
Yes it does not fully resolve the issue, but as noted in [this comment](https://github.com/mikaelacaron/Basic-Car-Maintenance/issues/200#issuecomment-1773839057) this isn't really the ending solution, the main objective is to have an onboarding UI that will have the user create a vehicle

**Comment by mikaelacaron** [comment]
@chrisjniles 
Thanks for wanting to contribute! Hacktoberfest ended on October 31, if you can still finish this issue by Saturday November 4, I’ll accept it, but otherwise after that I’ll be un-assigning all issues and cleaning up the code to ship this app to the App Store

**Comment by windrunner21** [comment]
Hi again! Can I be assigned to this issue @mikaelacaron
