### ISSUE TITLE
IMPROVE - Set fastlane version

### ISSUE THREAD

**Issue by elmoritz** [mikaelacaron/Basic-Car-Maintenance#204]
## Describe the feature you want to improve

I saw that there was a gemfile added to the repo, which only includes the fastlane gem.
It would be good to also set a version or at least commit thegemfile.lock to make sure everyone is using the same fastlane version.

From the [documentation](https://docs.fastlane.tools/getting-started/ios/setup/):
```
Bundler

It is recommended that you use Bundler and Gemfile to define your dependency on fastlane. This will clearly define the fastlane version to be used and its dependencies, and will also speed up fastlane execution.

Install Bundler by running gem install bundler
Create a ./Gemfile in the root directory of your project with the content
source "https://rubygems.org"

gem "fastlane"
Run bundle update and add both the ./Gemfile and the ./Gemfile.lock to version control
Every time you run fastlane, use bundle exec fastlane [lane]
On your CI, add bundle install as your first build step
To update fastlane, just run bundle update fastlane
```

Using fastlane the way it is implemented right now, will eventually break when fastlane updates

## Describe alternatives you've considered

You can also add a limit to the gemfile itself like:

```ruby
gem "fastlane", "~>2.216.0" # same as ">= 2.216.0", "< 2.217.0"


gem "fastlane", "~>2.216" # same as ">= 2.216", "< 3.0"

```
Don't know if any of these 2 version will actually do the trick, since the first will basically be stuck on this release and the second one will do all updates till 3.0

**Comment by mikaelacaron** [comment]
What would be the best practice? To update to 3.0, or using a specific version, and only update after it's been tested? @elmoritz

**Comment by elmoritz** [comment]
I would only add the gemfile.lock to the repository, since it is just like any other lock file.
It locks fastlane to one version and only if you want to updates the lock file.

At least you make sure that everyone is using the same version, when you also commit the gemfile.lock.

CI will always use the most recent version and you can not compare your local build/run vs CI build/run.

**Comment by mikaelacaron** [comment]
I did this sometime, I forget which PR
