### ISSUE TITLE
IMPROVE - Make AddVehicleView more interactive

### ISSUE THREAD

**Issue by sergpryimachuk** [mikaelacaron/Basic-Car-Maintenance#208]
## Describe the feature you want to improve

1. Vehicle Make field:
There's a constant number of vehicle makers, so we can add a picker to simplify filling the form.

2. Year field:
Adding a year can also be implemented with a picker.

3. VIN and licence number fields:
Those are usually uppercase, so we can add .textCase(.uppercase) view modifier to reinforce the format (user still will be able to change text case).

## Describe alternatives you've considered
- N/A

**Comment by sergpryimachuk** [comment]
I suggested this improvement, so I'd like to work on it 👀

**Comment by mikaelacaron** [comment]
> There's a constant number of vehicle makers, so we can add a picker to simplify filling the form.

but it's a gigantic list, that can always change. where does the data come from? how does it stay updated?

> Adding a year can also be implemented with a picker.

For what range of years? There's a gigantic list of years to add and pick through and I think it's easier and faster to type in the exact year

> Those are usually uppercase, so we can add .textCase(.uppercase) view modifier to reinforce the format (user still will be able to change text case).

I think this is a good change

**Comment by sergpryimachuk** [comment]
@mikaelacaron,

> but it's a gigantic list, that can always change. where does the data come from? how does it stay updated?

It's very rare that a major car brand appears overnight. I think we can add a json file or just an Array of Strings of all known brands + leave an option to enter manually. I found [this gist with all car brads](https://gist.github.com/pcgeek86/78f4cad29dd16961ceeeee654127a0db) that might be in handy. 

Maybe we can make not a picker but some popping out suggestions. I imagine how it can be done with a nice animation, just check out [my small demo here](https://share.cleanshot.com/1cXyl4Bl). 

> For what range of years? There's a gigantic list of years to add and pick through and I think it's easier and faster to type in the exact year

I guess you're right. So we can just add .keyboardType(.numpad) and some validation to limit the input to 4 characters only.

Also, you can check out how the adding vehicle form done in [a similar app](https://apps.apple.com/app/id1602075269).

**Comment by mikaelacaron** [comment]
I'll look at this later, don't start working on this yet.

Also I'm not a fan of the demo because it's kinda weird behavior for a scrolling searching list to suddenly appear from a text field

I'd like it better as a selection option, that pushes a list, and then that list has a search bar

**Comment by mikaelacaron** [comment]
Can you only make a change to use the number pad for the year, and all caps for the license plate number and VIN?


I don't want to constrain a list of car manufacturers, also I don't think it's a good experience, constraining brands and models because it's a long list that has to be updated, and the experience is annoying to me when you have to wait for models to load after selecting the make

**Comment by sergpryimachuk** [comment]
> Can you only make a change to use the number pad for the year, and all caps for the license plate number and VIN?

Sure, I can do that 😌

> I don't want to constrain a list of car manufacturers, also I don't think it's a good experience, constraining brands and models because it's a long list that has to be updated, and the experience is annoying to me when you have to wait for models to load after selecting the make

Indeed, the model list is much longer and might change time to time. So I didn't suggest adding models yet - only brands. 

It's a product decision. I leave it up to you 👍

Anyway, adding a vehicle is just one/two time action. But on the other side, it might be a part of onboarding, so good to have the best possible experience 🤔

**Comment by mikaelacaron** [comment]
> But on the other side, it might be a part of onboarding, so good to have the best possible experience 🤔

Yes eventually I want this as part of the onboarding! I've gone through several car sites when I was selling my vehicle and I always found it annoying to use a dropdown list for selecting the manufacturer (make), I'd rather type it in.

That was a website, but on a mobile app I feel the same, as of right now. I do think a list with a search would be the best (but not in the way you originally designed it). But also like you said as of right now, this isn't a task someone will be doing daily, so I'm not worried for now
