### ISSUE TITLE
BUG - `DashboardView` events Aren't Loading on the First Load

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#210]
## Describe the bug
* The `MaintenanceEvent`s on the `DashboardView` aren't loading, when the app is first loaded. Instead it's showing the empty screen that says "Add your first maintenance event"

## To Reproduce
1.  Add at least one vehicle and at least one maintenance event
2. Make sure the first tab that is going to open is the `Dashboard` (it saves the last tab when the app was closed)
2. Run the app and wait for the app to load and show events
3. The events never load, and it only shows the "empty view" that says `Add your first maintenance`

## Expected behavior
* The `Dashboard` tab loads the data even when it's the first tab to be open, you do **NOT** need to tap to a different tab, and tap back to see data

## Screenshots
* N/A

## Device Info (please complete the following information):
 * Device: iPhone 15 Pro Simulator
 * OS: iOS 17.0
 * App Version: v1.0 (1)

## Additional Context
* Add any other context about the problem here.

**Comment by anupdsouza** [comment]
@mikaelacaron , can I look into this while I wait for my existing PR to be merged ?

**Comment by mikaelacaron** [comment]
Yes because your other PR is CI related!
If it was iOS code related, I'd prefer to have you wait until your PR is merged incase there are changes you need to make

**Comment by hanhqvu** [comment]
@mikaelacaron Since anup unassigned themselves, could I take over this?

**Comment by hanhqvu** [comment]
@mikaelacaron This bug seems complicated that I thought. I checked and it seems the `DashboardViewModel` deinit which is why `events` are no longer stored in memory. I tried replacing with `@State events` and it seems to be okay. I will need some more time to investigate if okay with you. I will close the PR for now.

**Comment by hanhqvu** [comment]
More info on when the view model get deinit:
- 1st load or from background to foreground: `.task` get called then `deinit` get called => No events
- Switch from other tabs: `.task` get called then `deinit` doesn't get called =>  Events are shown

**Comment by mikaelacaron** [comment]
> I tried replacing with @State events and it seems to be okay

This shouldn't need to happen, because the `DashboardViewModel` is `@Observable`

But hmm yeah this seems like it might be tricky

**Comment by hanhqvu** [comment]
Sorry for being unclear, I mean change `events` to `@State` within the view itself.
This is kinda tricky but I'm thinking it has something to do with `scenephase`, since the `view model` get `deinit` only `scenephase` changes

**Comment by hanhqvu** [comment]
Probably not gonna be done in time for `hacktoberfest` but if it's okay with you, I'll keep looking into this & keep you updated.

**Comment by mikaelacaron** [comment]
> Probably not gonna be done in time for hacktoberfest but if it's okay with you, I'll keep looking into this & keep you updated.

That's fine, I'll look back into this afterwards too before I publish it to the App Store, but I believe this was working at first, so you may be able to go back in the commits and look for a time when it was working

**Comment by windrunner21** [comment]
Hey @mikaelacaron! Would be happy to help you with this issue. Are there any deadlines?

**Comment by mikaelacaron** [comment]
If you could finish it by Dec 1 that would be great! Thanks!

**Comment by windrunner21** [comment]
Hi again @mikaelacaron. I have opened a pull request. Waiting for the review, hope it helps! Good luck and thanks again!

**Comment by mikaelacaron** [comment]
Thanks so much!! I'll review it soon! I love how small of a fix it was
