### ISSUE TITLE
Updating an Odometer Reading

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#211]
## Describe the feature you want to improve
* Add a swipe action to swipe left on a row for an odometer reading on the `OdometerView` and show an edit view as a sheet
* The sheet should be called `EditOdometerReadingView` and put in the correct folder
* Show a sheet to edit the values for that `OdometerReading`

See how the code works for editing a `MaintenanceEvent` on the `DashboardView`, this view should work in the same way

## Describe alternatives you've considered
* N/A

**Comment by abhinavs1920** [comment]
I want to work on this issue

**Comment by ShaniDan** [comment]
Hi Mikaela. 
Can I work on this issue? I did a similar view in my personal project.

**Comment by mikaelacaron** [comment]
You got it! See how it's implemented in the `DashboardView` I'd like this implemented in a similar way
