### ISSUE TITLE
Swipe to Delete an `OdometerReading`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#212]
## Describe the feature you want the app to have that it currently doesn't
* Add a swipe action to swipe left to delete a reading from the `OdometerView`

## Describe alternatives you've considered
* See how the swipe to delete functionality works for a `MaintenanceEvent` on the `DashboardView` and this should function the same way

## Additional context
* Add any other context or screenshots about the feature request here.

**Comment by Marcel-git666** [comment]
May I take this as a second issue?

**Comment by mikaelacaron** [comment]
I labeled this one `first-timers-only` so it's only for people who are new to the repo, and haven't yet contributed! Thanks!

**Comment by horacio3m** [comment]
I've already worked on an issue, but if you can't find anyone to work on this one, I'd love to work here. I've never worked with drag gestures before, it would be nice to learn and try this one. Gimme a shout

**Comment by mikaelacaron** [comment]
@horaciomota thanks for the offer! Right now I'm leaving it open to anyone who hasn't contributed yet, for the rest of Hacktoberfest.

Later afterwards, I may open this up to anyone who wants to continue contributing after October

**Comment by Wilsonilo** [comment]
Hey Mikaela, I just joined the community a couple of months back and would love to give it a shot on this one. Will follow the instructions, fork, use the dev branch, etc. Just want to be sure that my branch for this issue would be 212-swipe-to-delete-an-odometerreading based on your guide, name a little long just want to be sure.

**Comment by mikaelacaron** [comment]
> 212-swipe-to-delete-an-odometerreading

The branch name isn't super important! Because in the end it won't matter, but following common conventions that name works or you could do `212-swipe-to-delete` which is fine

Assigned to you 👍

**Comment by Wilsonilo** [comment]
@mikaelacaron I'm pretty much done, you've already put the code in another place so thanks, I was just wondering about tests and documentation is there a need for me to add any tests and comments for my implementation or this is something that is not part of the contribution part. Thanks, after this I'll submit my PR.

**Comment by mikaelacaron** [comment]
nah no need to add any tests! (how it's coded right now it's not super testable), that's something I'm looking at changing after Hacktoberfest @Wilsonilo
