### ISSUE TITLE
IMPROVE - SettingsView Vehicle List

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#213]
## Describe the feature you want to improve
* When a user doesn't fill in all of the vehicle information, it shows as blank space on the `SettingsView`
* Fix this so that the text only shows when there is a value

## Describe alternatives you've considered
* N/A

## Screenshot
![Simulator Screenshot - iPhone 15 Pro - 2023-10-24 at 01 13 26](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/3b782c5a-8c94-4eb4-85c9-36ab23434302)

**Comment by TratonGossink** [comment]
Hi Mikaela, 

Can I have this issue? 
I did something similar to this in a chat app list view.

**Comment by horacio3m** [comment]
@TratonGossink I think a simple way to do this would be to place the text fields in the same stack with a minimum height. A second option would be to put default text to appear when there is no input data. This would maintain the element's height
I would love work on this issue, if its available. 
I wd love to work or help on this issue if its available.

**Comment by mikaelacaron** [comment]
> second option would be to put default text to appear when there is no input data

it would be weird to have default values that are not real, for information you haven't filled in

I think it's totally fine for there to be different sizes for each row (depending on the info that's there)


@horaciomota thanks for the help, but it is only one assignee per issue!

**Comment by mikaelacaron** [comment]
@TratonGossink 
Thanks for wanting to contribute! Hacktoberfest ended on October 31, if you can still finish this issue by Saturday November 4, I’ll accept it, but otherwise after that I’ll be un-assigning all issues and cleaning up the code to ship this app to the App Store

**Comment by TratonGossink** [comment]
Hi Mikaela,
I'm ready for a pull request for this issue. I have never done a pull request before and might need a little coaching through it. 🙃

**Comment by mikaelacaron** [comment]
@TratonGossink  I'd recommend watching a tutorial and googling how to make a pull request to an open source repo! you can do it!

Also I go through this in my [livestream](https://www.youtube.com/live/-rYYKXrCyro?si=eJRdmLORh9Po4B5a)! you can watch that for a real time, how this is done
