### ISSUE TITLE
FEATURE - Add TipKit

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#214]
## Describe the feature you want the app to have that it currently doesn't
* Implement a TipKit tip that shows a user on the `SettingsView` that this an app that's open source and that anyone can contribute to this project if they're interested in iOS development with Swift

## Describe alternatives you've considered
* N/A

## Additional context
* I haven't used TipKit yet, but I did not want to make a tip pointing to the `+` button because that feels obvious and self explanatory. If you have any other ideas for a tip, comment below what you want to implement it and @mikaelacaron will approve it (if it's different than what's described above)

**Comment by SandroDahl** [comment]
Hey @mikaelacaron  can I implement this feature? How do you find this representation of the tip? 

<img src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/2863724/f2b99b6b-ed3c-4e5b-b42c-11e8f66ab4ac" width=33% height=33%>

**Comment by mikaelacaron** [comment]
yeah! Can you "anchor" it to the GitHub repo row? rather than the heading
