### ISSUE TITLE
IMPROVE - ProgressView When Loading Contributors Avatars

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#215]
## Describe the feature you want the app to have that it currently doesn't
* Right now when loading the `ContributorListView` a default static image `person.circle` is shown when the image is loading.
* Instead show a `ProgressView` that the image is loading

## Describe alternatives you've considered
* N/A

## Additional context
* See current functionality

https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/227e4855-6809-4693-8d84-fa01f176aea9

**Comment by Marcel-git666** [comment]
Hi Mikaela,

Can I have this issue?

**Comment by mikaelacaron** [comment]
You got it!

**Comment by Marcel-git666** [comment]
Done. At least I hope I got it right.
