### ISSUE TITLE
Create a New DocC Documentation Interactive Tutorial to Update a Branch

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#216]
## Describe the feature you want the app to have that it currently doesn't
* Create a new DocC [interactive tutorial](https://www.swift.org/documentation/docc/tutorial-syntax) with instructions about how to update your feature branch, after you've made a PR, and there are changes on the `dev` branch that need to be merged into your feature branch

## Describe alternatives you've considered
* This could be a whole step by step for beginners, or the other alternative is adding steps or a new section to the Getting Started tutorial with a link to a good YouTube video about how to do this

## Additional context
* Getting started is Chapter 1, this issue would be labeled "Chapter 2"

<img width="759" alt="Screenshot 2023-10-24 at 1 38 52 AM" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/20238e3b-0486-43e2-ba77-4f870aa3f566">

**Comment by Jakayus** [comment]
Hey @mikaelacaron can I take this one?

**Comment by mikaelacaron** [comment]
Yes! Are you planning on writing a tutorial, or linking a YouTube video? (I suggested both in the issue) @Jakayus

**Comment by Jakayus** [comment]
Thank you! And yeah I would like to do the tutorial through steps - I think the aspect of scrolling down and seeing the changes on the side bar is pretty cool. I've never worked with DocC so figured now's a good time to learn.

Did one of your livestreams go over the steps used for the tutorial? I could follow along that flow and use that for the basis of this issue. @mikaelacaron

**Comment by mikaelacaron** [comment]
Yup here's the [livestream](https://www.youtube.com/live/-rYYKXrCyro?si=pB6IkPr4oWM97pv8)! Sorry I haven't had time to add timestamps to it yet

I'd love to see the full interactive tutorial! 😍 

Please use git with the Terminal (because those commands will be the same for everyone)

Please download and use [OhMyZsh](https://ohmyz.sh/) for your terminal, because it removes your name from the main prompt thing, and shows the directory you're in and the branch (which can help it be clearer in instructions0

And be sure to increase your font a little bit! to make it more readable (see the Getting started tutorial that's already there), there's some photos that are easier to read than others

**Comment by Jakayus** [comment]
Thank you for the pro tips!! This is getting me pumped as now I get to learn to make cool fancy follow-along docs haha.  I'll be able to start diving into it tomorrow night, so in the meantime I can go through the livestream and any DocC articles. 

Do you prefer any questions through here or through social media DMs?

**Comment by mikaelacaron** [comment]
any more questions about this issue, ask me in DM's cause there's better notifications.

If it's something specific about git and branching and making the PR, put it here

**Comment by lamel0rd** [comment]
Is the issue still OPEN?

**Comment by lamel0rd** [comment]
Would like to contribute upon

**Comment by mikaelacaron** [comment]
@akoolarni No this issue is not open because @Jakayus is working on it, please comment on a different issue where there is no assignee! thank you!

**Comment by Jakayus** [comment]
@mikaelacaron quick status update - I had last minute work stuff pop up during the week that stopped my progress, but I'm aiming to have a PR tonight or tomorrow morning! I'll have tons of time after the iosDevHappyHour so I should be able to get to it with no distractions. fyi
