### ISSUE TITLE
BUG - DocC Tutorial Isn't Deployed

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#217]
The Getting Started Tutorial Shows in the Documentation in Xcode, but it is not being shown on the [documentation site](https://mikaelacaron.github.io/Basic-Car-Maintenance/documentation/basic-car-maintenance/documentation/) that's generated from the GitHub Action, [docc.yml](https://github.com/mikaelacaron/Basic-Car-Maintenance/blob/dev/.github/workflows/docc.yml)

<img width="992" alt="Screenshot 2023-10-24 at 1 41 48 AM" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/2fe253d0-26e5-48c2-993f-8db64e4ccefa">

* This bug fix would be fixing the `docc.yml` file to also deploy the tutorials to the documentation site

**Comment by ampsonic** [comment]
Happy to take this as well.

**Comment by ampsonic** [comment]
I am having a bit of trouble with this one. @rizwankce Do you have any pointers on where I should look to get this documentation added to the github action?

**Comment by rizwankce** [comment]
@ampsonic guess we only need getting started markdown file on the project somewhere to fetch it correctly. I see only tutorial file as of now on the repo. 

We probably need something like [this](https://github.com/simonbs/Runestone/blob/main/Sources/Runestone/Documentation.docc/GettingStarted.md) one.

**Comment by ampsonic** [comment]
Hi @mikaelacaron I'm going to release this to someone else, I'm not sure what to do and probably won't have time. 

Sorry!

**Comment by Jakayus** [comment]
Hi @mikaelacaron can you assign this to me? (This is not for Hacktoberfest).  I have a vested interest since I want to see the interactive tutorials hosted lol.

**Comment by mikaelacaron** [comment]
@Jakayus go for it! haha

**Comment by mikaelacaron** [comment]
Re-opening this because the tutorial is now linked, but it's not shown in the side bar, maybe how [this project](https://github.com/simonbs/Runestone/blob/main/.github/workflows/deploy_documentation.yml) does it, may help? (as mentioned in [this comment](https://github.com/mikaelacaron/Basic-Car-Maintenance/issues/217#issuecomment-1783989259))

**Comment by Jakayus** [comment]
Thank you for linking that again! I was not paying good attention to their documentation the first time, since it's clearly working fine in theirs.

If I don't have significant progress by the end of the weekend I may end up un-assigning myself to let someone else take a shot, but I'll do my best to get it situated this time.

**Comment by mikaelacaron** [comment]
That works! It's all good! Use I know the holidays are coming up this weekend too!
