### ISSUE TITLE
FEATURE - Create an enum for SFSymbols to Replace Stringly Typed Symbols

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#227]
## Describe the feature you want the app to have that it currently doesn't
* Create an enum called `SFSymbol` to use type safe SF symbol variables throughout the project
* Replace the stringly typed SF symbols with the new enum

```swift
enum SFSymbol {
   static let filter = "line.3.horizontal.decrease.circle"
   static let plus = "plus"
}
```

## Describe alternatives you've considered
* N/A

## Additional context
* Add this to the Constants file that's already in the project, do not create a new file
* Only replace the SF symbols that are being used in the app, there is no need to make a giant enum with every SF symbol possible

**Comment by Candy505** [comment]
Hey! Kindly assign me this issue.  @mikaelacaron  I also have a question, I am sorry if it sounds lame but I have not worked in this tech stack before but as it is labelled good first issue I wanna give it a try. What I can gather from this issue is -

1. I am supposed to make changes in constant file
2. And then do I need to make changes for the enum  in all the project ? "Replace the stringly typed SF symbols with the new enum", this is what you mean by this line right ?

Thankyou.

**Comment by mikaelacaron** [comment]
1. Yes
2. Yes where any SF symbol is used, you need to replace the string, with a newly created property from the enum

This is an iOS project with Swift and SwiftUI. It requires a Mac and you must have Xcode downloaded. Some familiarity with this stack is necessary

**Comment by Candy505** [comment]
@mikaelacaron well Sorry then I won't be able to contribute. No mac and no familiarity, thankyou for your time;-;

**Comment by horacio3m** [comment]
@mikaelacaron do you need just the enum? I would love work on it. Could assign me this issue?
One question... any other way to see which SF icons are being used in the app besides searching manually? I know it's a silly question, but it doesn't hurt to ask. xD

**Comment by mikaelacaron** [comment]
yup only create an enum with only the symbols that are used in the app

> any other way to see which SF icons are being used in the app besides searching manually? I know it's a silly question, but it doesn't hurt to ask. xD

to see, look at how one is used, and you'll notice the same parameter name that's used before each of them (then search that parameter name throughout the project)
* so that's not the exact answer, but it'll give you the right direction
