### ISSUE TITLE
Add  CI Passing Badge to the README

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#235]
## Describe the feature you want the app to have that it currently doesn't
* Add a CI unit tests passing badge to the readme, and replace the hard coded "Build passing" one
* This should relate specifcally to the Unit tests passing in GitHub Actions for this repo

## Describe alternatives you've considered
* N/A

## Additional context
* This should only relate to the unit tests passing in GitHub Actions
* The code can be created by clicking this button in the Actions tab
<img width="1211" alt="Screenshot 2023-10-27 at 2 28 48 PM" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/ada471d2-485e-40fd-a8ef-b73ed71538c4">

**Comment by allanmaral** [comment]
@mikaelacaron I’d like to work on this issue!
