### ISSUE TITLE
BUG - Vehicle with empty details getting saved

### ISSUE THREAD

**Issue by ayushs-2k4** [mikaelacaron/Basic-Car-Maintenance#24]
## Describe the bug
* Vehicle getting added without even filling the details.

## To Reproduce
1. Go to 'Settings'
2. Tap on the button 'Add Vehicle'
3. Do not fill in any details
4. Tap on 'Add' Button
5. Empty details Vehicle will be saved

## Expected behavior
* Vehicle should not get added.

## Screenshots
![Simulator Screenshot - iPhone 15 Pro - 2023-10-01 at 19 17 52](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/63922782/4a245328-aa69-4b80-a204-e464c5c6abff)

## Device Info (please complete the following information):
 * Device: Phone14 Pro
 * OS: iOS 17.0
 * App Version 1.0(1)

## Additional Context
* N/A

**Comment by ayushs-2k4** [comment]
I am working on this issue.

**Comment by mikaelacaron** [comment]
@ayushs-2k4 Good catch!

Be sure to fill in every section of the template, this section was left blank /  the default template
> Describe the bug
A clear and concise description of what the bug is.

**Comment by ayushs-2k4** [comment]
Oh, it slipped from my eyes to write description of bug. BTW, I have submitted a PR fixing the bug by adding a check before saving a new Vehicle.

**Comment by mikaelacaron** [comment]
Closed with #32
