### ISSUE TITLE
BUG - Add Maintenance behaviour is inconsistent when no vehicle added to the app

### ISSUE THREAD

**Issue by darrengillman** [mikaelacaron/Basic-Car-Maintenance#261]
## Describe the bug
When no vehicle has been added (or all vehicles have been deleted) the Add Maintenance view is available but is not fully functional as a vehicle is required to add a maintenance record.

As a consequence of this:
- on the Add Maintenance screen the "Add" button is enabled as soon as a title has been added but does not commit the record and does not present any alert detailing why it can't.  Could leave the user hanging.
- The Vehicle section of the form says "select vehicle" but there's no picker available.

## To Reproduce
1. Use either a clean install or delete all vehicle entries
2. Go to the Dashboard
3. Click the "+" button to add a maintenance record
4. Add a title
5. At this point see that
    - the "Add" button is enabled
    - clicking "Add" has no obvious behaviour to the user, and give no indication of where to go next
    - the lack of a picker on the Vehicle entry

## Expected behavior
Several possible behaviours (some app architecture-dependent):
- clicking on the "+" gives an alert saying "add a vehicle" if none present rather than entering the Add Maintenance view
- clicking on  the "+" loops the "Add Vehicle view in before the Maintenance view
- clicking the "+" open the maintenance view, put a "no vehicle" entry in the picker, keeps the "Add" button disabled, and presents an alert explaining where to go

In all instances, and as a minimum, the "Add" button should not enable until all the mandatory fields have been completed.

## Screenshots
<img width="470" alt="image" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/12803226/cc31eccd-5a2e-4ce8-b2d6-46425ee269fc">

## Device Info (please complete the following information):
 * Device: Simulator
 * OS: 17.0
 * 1.0

## Additional Context
N/A

**Comment by mikaelacaron** [comment]
@darrengillman yes this is an issue! But I'm going to be fixing this before shipping the app, by adding an onboarding view, that has the user enter their vehicle info. So this won't be an issue. I'll leave it open, and assign myself to this issue for now

**Comment by darrengillman** [comment]
@mikaelacaron fair enough.  And I was going to volunteer to fix it for you :-)  Although will need to mod the maintenance view to cope with the user deleting their vehicles.  

Do you still want us to offer to pick up issues, or would you rather just ship now?

**Comment by mikaelacaron** [comment]
If you could pick up #6 that would be great! (a person already did the work and the PR is closed, but there were some edits they never made in time, before Hacktoberfest ended)

Overall I didn't really expect many people to keep contributing after Hacktoberfest, and yeah at the moment I might just pause most of the issues until I ship the app, because I'll be making some big changes. See #260 for the list of things I'll be doing before shipping

**Comment by darrengillman** [comment]
@mikaelacaron apologies for dropping the ball on this.  A third party API our primary business app uses withdrew it services without notice or documentation, so it's been a manic couple of weeks building an alternative solution.  Fun though, in a type 2 way!

**Comment by mikaelacaron** [comment]
No worries! I'll be picking this up when I implement the onboarding. I'm using #260 to track all the tasks left before I ship the app

**Comment by mikaelacaron** [comment]
Fixed with #287
