### ISSUE TITLE
FEATURE - Add description on dashboard screen

### ISSUE THREAD

**Issue by daljeetseera** [mikaelacaron/Basic-Car-Maintenance#28]
## Describe the feature you want the app to have that it currently doesn't
* Currently, the app opens with blank dashboard. I would like to add a description which helps user to take an action. 

## Describe alternatives you've considered
* A description with ```Add maintenance``` button which directly opens the add sheet.

## Additional context
* Screen must have a description with/without an action button.

**Comment by daljeetseera** [comment]
Can I start on this one? @mikaelacaron

**Comment by mikaelacaron** [comment]
I think a description would be best! Adding another button could be confusing

**Comment by mikaelacaron** [comment]
Closed with #31
