### ISSUE TITLE
BUG - Default language issue

### ISSUE THREAD

**Issue by rbennum** [mikaelacaron/Basic-Car-Maintenance#281]
## Describe the bug
After the last PR merged, the default language changed to Polish.

## To Reproduce
1. Build and open the app.

## Expected behavior
I expect the app's default language to be English.

## Screenshots
![photo_2024-01-01_20-49-50](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/8705838/18e738f1-af0a-4fce-a727-f4c2229d1d12)

**Comment by maartinj** [comment]
Option+Command+R when launching simulator, change 'App Language' to 'System Language' and 'App Region' to 'System Region' will not work here?

<img width="919" alt="Zrzut ekranu 2024-01-3 o 02 05 44" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/53284922/c9d45d7b-1a06-4958-aa8a-9105a33c3ef6">

**Comment by rbennum** [comment]
@maartinj hi, thank you for replying to my concern. I think what you showed me should work. The problem perhaps lies when you also pushed the changes on xcschemes [here](https://github.com/mikaelacaron/Basic-Car-Maintenance/pull/280/files#diff-fe2dc746730709cd508c167e7a2186c3d257748cf68bb3e8157bdbd86a467b44). Removing this should solve the problem.

**Comment by maartinj** [comment]
Hi @rbennum,

Oh apologize for that. Seems that I left during Option+Command+R when launching simulator, with 'Polish' language in 'App Language' instead of 'System Language'.

I will request new PR to @mikaelacaron for checkout and to merge fix to the dev branch.

Thank you for vigilance and apologize for the confusion.

**Comment by rbennum** [comment]
@maartinj glad to help!

**Comment by mikaelacaron** [comment]
All good @maartinj ! it happens, haha I didn't notice either

**Comment by mikaelacaron** [comment]
@rbennum Thanks for reporting it!

**Comment by rbennum** [comment]
@mikaelacaron you're welcome!
