### ISSUE TITLE
IMPROVE - Empty `DashboardView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#286]
## Describe the feature you want to improve
* `DashboardView` has this text when the view is empty (meaning a user hasn't added their vehicle yet)
* Add a button below this text that says "AddVehicle" and show the `AddVehicleView` as a sheet

```swift
if viewModel.events.isEmpty {
Text("Add your first maintenance", comment: "Placeholder text for empty maintenance list prompting the user to add a maintenance event")
   // ...
}
```

> [!NOTE]
> Leave the closure for `AddVehicleView` `nil` because this will be something that is going to be in a different PR (the actual functionality to add a vehicle is in the `SettingsViewModel`, and not accessible here), and I want that refactor in a different PR

## Describe alternatives you've considered
* N/A

**Comment by ItsJakeMarcus** [comment]
This looks like a fun one :)
