### ISSUE TITLE
User build setting separation

### ISSUE THREAD

**Issue by mattmassicotte** [mikaelacaron/Basic-Car-Maintenance#3]
## Describe the feature you want the app to have that it currently doesn't

After cloning, building this project will fail to build because the signing team configuration is set up for the authors. The fix is straightforward, but you have to know how to change your signing set up. It is possible to extract this information out and offer clearer instructions for new developers.

## Describe alternatives you've considered

What I like to do is separate out the signing information into a dedicated xcconfig file. This way, you can write more explicit instructions about what is required to get the app building and running. I thought about just making a PR to do this, but hesitated because:

- It is a fairly invasive change to the .xcodeproj, and merge conflicts are likely
- It requires a change to the .gitignore file, which was a lot more complex than I was expecting

## Additional context

But I'm still up for helping! I use a similar technique in this repo here:

https://github.com/chimeHQ/Chime#building

**Comment by mikaelacaron** [comment]
@mattmassicotte thanks for pointing this out! I'll do this 👍

**Comment by mikaelacaron** [comment]
@mattmassicotte  Implemented!
