### ISSUE TITLE
FEATURE - Tinted App Icons for iOS 18

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#305]
## Describe the feature you want the app to have that it currently doesn't
* Create tinted versions for the app icon, and the alternative app icons
* Add the tinted versions to the app in the right place in Assets in the project

## Describe alternatives you've considered
* N/A

## Additional context
* You will need to be added to Figma for this, it's a private board for right now, but I could make it open so anyone could view if you think it's useful

**Comment by rajhraval** [comment]
Would love to take issue.

**Comment by mikaelacaron** [comment]
@rajhraval you got it! On some social media, DM me your email, and I'll add you to Figma

**Comment by rajhraval** [comment]
Done, I have DMed on X
