### ISSUE TITLE
IMPROVE - Setup SwiftLintPlugins

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#306]
## Describe the feature you want to improve
* Setup the [SwiftLintPlugins](https://github.com/SimplyDanny/SwiftLintPlugins) in the project as opposed to the original method, which was using a build phase in the project

## Describe alternatives you've considered
N/A, if anything else is suggested, let Mikaela know!

**Comment by hanhqvu** [comment]
@mikaelacaron 
hello again! I'm happy to pick this up if it's available!

**Comment by mikaelacaron** [comment]
@hanhqvu nice to see you back! ❤️ 
yup you got it!

**Comment by hanhqvu** [comment]
@mikaelacaron 
this is to confirm my assumption
I assume I need to setup SwiftLint to be run as a command
is that correct?

**Comment by mikaelacaron** [comment]
uhhmmmm I haven't done this honestly, so I'm not completely sure of your question, it's moving it to be run as a plug-in in Xcode as opposed to being a build script phase

Which seems to be the way that they want you to use it now?

**Comment by hanhqvu** [comment]
@mikaelacaron
ah, I misunderstood it as moving to use the command line
I'll proceed with setting up the build plug-in
