### ISSUE TITLE
Add `private_swiftui_state` SwiftLint rule and resolve the warnings

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#308]
## Describe the feature you want to improve
Add `private_swiftui_state` SwiftLint rule (notice they're in alphabetical order) and resolve the warnings

**Comment by aking618** [comment]
@mikaelacaron Is it alright if I tackle this issue?

**Comment by mikaelacaron** [comment]
You got it! @aking618
