### ISSUE TITLE
Build All Previews and Update with `@Previewable`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#309]
## Describe the feature you want to improve
* Some SwiftUI previews are failing, make sure they all build and you can preview what's intended for that view
* Make sure they all use the `#Preview` macro
   * If needed use the new `@Previewable` macro where needed 
      * https://www.avanderlee.com/swiftui/previewable-macro-usage-in-previews/

## Describe alternatives you've considered
* N/A

**Comment by Yashraj49** [comment]
hey @mikaelacaron I am good to see this project for this years Hacktoberfest ,so I would like to get started with this issue kindly assign it to me.

**Comment by mikaelacaron** [comment]
@Yashraj49 youre good to go!
