### ISSUE TITLE
Create `PrivacyInfo.xcprivacy` file

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#310]
## Describe the feature you want to improve
* Update the empty file `PrivacyInfo.xcprivacy` file with the correct information, for this project (be sure to just update the file and not create a new one)
* This project uses Firebase (Firestore, Auth, and in the future Storage)

This website will be helpful to generate the file, but you need to choose what goes into the file

https://www.privacymanifest.dev/

**Comment by AimeeT8** [comment]
Hi Mikaela, Can you assign this issue to me? Thank you!

**Comment by mikaelacaron** [comment]
You got it!
