### ISSUE TITLE
Update Getting Started DocC Documentation

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#311]
## Describe the feature you want to improve
* Update the Getting Started tutorial documentation with the new steps from [CONTRIBUTING.md](https://github.com/mikaelacaron/Basic-Car-Maintenance/blob/dev/CONTRIBUTING.md) about how to setup Firebase Local Emulator

**Comment by Vai-Man** [comment]
Hey can I work on this?

**Comment by mikaelacaron** [comment]
@Vai-Man you got it!
