### ISSUE TITLE
IMPROVE - Build the App for macOS

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#315]
## Describe the feature you want the app to have that it currently doesn't
The project was originally going to be a multi-platform application, and I would love to see it get there at some point! We're going to start, by being able to build the application for macOS

## Additional context
Right now the build fails because macOS doesn't import UIKit (which makes sense haha), but also another few errors. Resolve those so that we can at least build for macOS!

This may require some modifications to work with the Firebase emulator? (I think), but also checking Firebase is compatible

**Comment by narwalayush4** [comment]
Hi Mikaela, I would like to work on this issue.

**Comment by mikaelacaron** [comment]
You got it!
Just work on making it build, don't worry about any optimizations to make it look better on macOS, let me know afterwards, and we can make new issues for that!
You could start a [discussion](https://github.com/mikaelacaron/Basic-Car-Maintenance/discussions) about it

**Comment by mikaelacaron** [comment]
@narwalayush4 also note there's a top level `Shared` Folder

Create a new folder, at the same level, called `macOS` is there's any macOS specific changes or extensions that are needed, and make the folders the same hierarchy like `Odometer` if there's only changes needed for macOS, for the Odometer related views or viewModels

**Comment by narwalayush4** [comment]
I am not able to sign the app for building it for macOS. It works fine for iOS simulator. I think the issue is that it treats my mac as a real device and not a simulator. 

I was able to remove the Sign-In with Apple Capability from main target build it. But still the wirdget extension doesn't build with the following error. Could anyone help me out here?

"Your team has no devices from which to generate a provisioning profile. Connect a device to use or manually add device IDs in Certificates, Identifiers & Profiles. https://developer.apple.com/account/"

**Comment by mikaelacaron** [comment]
> I think the issue is that it treats my mac as a real device and not a simulator.

I think that's correct

You've setup the xcconfig file correctly? and it still doesn't work? (show an error other than "Your team has no devices from which to generate a provisioning profile. Connect a device to use or manually add device IDs in Certificates, Identifiers & Profiles."

**Comment by narwalayush4** [comment]
> You've setup the xcconfig file correctly?

Yep, I have. The app runs perfectly on an iOS Simulator. 

> show an error other than ?

It shows two errors both related to signing in the Widget Extension, but not the import UIKit error (which it should). 

- Communication with Apple failed
Your team has no devices from which to generate a provisioning profile. Connect a device to use or manually add device IDs in Certificates, Identifiers & Profiles. https://developer.apple.com/account/

- No profiles for 'com.CarApp.CarApp.Widget' were found
Xcode couldn't find any iOS App Development provisioning profiles matching 'com.CarApp.CarApp.Widget'.

**Comment by mikaelacaron** [comment]
okay yeah it seems like you'd have to create your own identifier in your apple account... which I don't really want every contributor to have to do that to work on macOS...
because try to run it on an iOS device (rather than the simulator), I bet you'd get the same error

**Comment by narwalayush4** [comment]
So, I was able to remove the signing errors by doing the following. Let me know if this is something that is feasible. 

- Remove Sign in with Apple Capability
- Add Mac Destination in the Widget Target 

See PR https://github.com/narwalayush4/Basic-Car-Maintenance/pull/1

<img width="1440" alt="Screenshot 2024-10-07 at 5 41 41 PM" src="https://github.com/user-attachments/assets/52ef59ea-9e4c-456b-81b1-8128f6ed2863">

**Comment by mikaelacaron** [comment]
Does removing Sign in With Apple also remove it for the iOS app? Or only the macOS target? @narwalayush4

**Comment by narwalayush4** [comment]
Sadly, it removes for the iOS app as well. 😢 

So, I believe we won't be proceeding with this?

**Comment by mikaelacaron** [comment]
@narwalayush4 ahhhh okay. Yeah let's discontinue this for now, I'll close the issue

But if you wanted to just look into open source macOS app dev and let me know if you find anything (how this would work for people to compile), that would be cool. But if not it's fine!

**Comment by narwalayush4** [comment]
I am trying to contritubute to https://github.com/CodeEditApp/CodeEdit, an open source code editor for macOS. It's pretty cool you can check it out.

**Comment by mikaelacaron** [comment]
thanks! @narwalayush4 I'll check it out how they did it!
