### ISSUE TITLE
IMPROVE - Contributing Docs

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#324]
## Describe the feature you want to improve
Improving documentation around downloading the latest version of Java for the Firebase emulators
Discussed here:
https://github.com/mikaelacaron/Basic-Car-Maintenance/discussions/317#discussion-7269696

* [x] Update the CONTRIBUTING.md
* [x] Update the DocC getting started doc

**Comment by mikaelacaron** [comment]
Created for @rramirez-dev please comment so I can assign you to it!

**Comment by rramirez-dev** [comment]
You can assign it to me

**Comment by rramirez-dev** [comment]
Which document is the DocC getting started doc?

**Comment by mikaelacaron** [comment]
`getting-started.tutorial` in`Documentation.docc`
