### ISSUE TITLE
Fix Unit Tests and Build Documentation GitHub Actions

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#325]
Fix unit tests and build documentation GitHub Actions

I've broken them on accident this year, and haven't been able to fix them yet

for unit tests I tried:
* I thought it was originally due to "pins" in the Package.resolved being set to `3` rather than `2` but that doesn't seem to be the issue
* I thought it was because of the name of the simulator being wrong, but that wasn't it either

In [Actions](https://github.com/mikaelacaron/Basic-Car-Maintenance/actions) you can see why they've failed recently

Unit tests uses Fastlane to run the unit tests, and GitHub Actions to trigger fastlane

The build documentation is triggered via GitHub actions and runs the `build-docc.sh` file

**Comment by OmarHegazy93** [comment]
@mikaelacaron I can give it a go

**Comment by mikaelacaron** [comment]
I'm working on this right now!

**Comment by OmarHegazy93** [comment]
Apologies @mikaelacaron, I had so many things on my plate last couple of days, I was trying locally and tests were passing when removing the derived data path, but I was still investigating. But it's totally fine if you wish take over

**Comment by mikaelacaron** [comment]
Solved! Thanks for working on it, I was working with a friend and able to fix it
