### ISSUE TITLE
IMPROVE -Vehicle Display in settings

### ISSUE THREAD

**Issue by rramirez-dev** [mikaelacaron/Basic-Car-Maintenance#332]
## Describe the feature you want to improve
Reformat how the vehicle details are displayed in the settings screen.

## Describe alternatives you've considered
N/A
![VehicleDisplay](https://github.com/user-attachments/assets/2a0c2c88-59e9-4afd-be83-4f6f17734c06)

**Comment by rramirez-dev** [comment]
You can assign this anyone who wants it.

**Comment by maartinj** [comment]
Only text? I can think of a way to improve this if @mikaelacaron can assign me.

**Comment by mikaelacaron** [comment]
@maartinj yes it would be reformatting to match the sceeenshot from Robert
