### ISSUE TITLE
IMPROVE - How the mileage is displayed on the `OdometerView`

### ISSUE THREAD

**Issue by rramirez-dev** [mikaelacaron/Basic-Car-Maintenance#336]
## Describe the feature you want to improve
Reformat the milage display on the odometer screen.

## Describe alternatives you've considered
![Screenshot 2024-10-09 at 9 43 17 PM](https://github.com/user-attachments/assets/3b54b6d6-8a0c-45f2-bc45-1219f26d1344)

**Comment by rramirez-dev** [comment]
This issue is open for anyone to take.

**Comment by ashabooga** [comment]
Hi there! How did you want this to be re-formatted?

**Comment by mitaligondaliya** [comment]
Hi, I'd love to work on this

**Comment by mikaelacaron** [comment]
@mitaligondaliya  I've labeled this as `first-timers-only` so it's only for people new who haven't contributed to the repo yet (and you have a PR pending that I'm going to review)

Could you choose a different issue? Thanks! I'll be making new issues soon too)

**Comment by mitaligondaliya** [comment]
> @mitaligondaliya I've labeled this as `first-timers-only` so it's only for people new who haven't contributed to the repo yet (and you have a PR pending that I'm going to review)
> 
> Could you choose a different issue? Thanks! I'll be making new issues soon too)

Sure! I'll pick a different issue. Looking forward to the new ones as well. Thanks!

**Comment by mikaelacaron** [comment]
thanks so much! making new ones tomorrow!

**Comment by kondayutarou** [comment]
Hey let me work on this on the weekend.
