### ISSUE TITLE
IMPROVE - Test Contributor Model

### ISSUE THREAD

**Issue by Drag0ndust** [mikaelacaron/Basic-Car-Maintenance#34]
## Describe the feature you want to improve
I want to add some Unit Test for models and other parts of the app where it is useful

**Comment by Drag0ndust** [comment]
I also want to do that if it is ok, @mikaelacaron

**Comment by mikaelacaron** [comment]
@Drag0ndust Only one issue at a time please. Unit test a single viewModel, because unit testing multiple will be changing too much code at once

**Comment by Drag0ndust** [comment]
ok, then I will rename the issue to the viewmodel I will test.
Are you assigning the correct labels because I can't do it

**Comment by mikaelacaron** [comment]
Done! Thank you!
