### ISSUE TITLE
FEATURE - PDF Export of Maintenance Events Only

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#342]
## Describe the feature you want the app to have that it currently doesn't
* Create a PDF export of the maintenance events ordered by oldest to newest of a single vehicle
* Add a toolbar button to start the export with `square.and.arrow.up` on the leading side of the `DashboardView`
   * Tapping this shows `ExportOptionsView` as a sheet
* Create a view called `ExportOptionsView` (in the `Dashboard` > `Views` directory) that's used to eventually select the options for how the PDF can be exported (making it more customizable, but for the start we'll only do specific things, listed below)
   * Select the vehicle to export using a picker
   * Export button

Full flow:
* Tap export button
* See `ExportOptionsView` as a sheet, it'll show a picker of the vehicles
* Tap an Export button (make this the trailing toolbar button of this view
* Export as described below as a PDF, that can be saved to a person's file's app or AirDropped to someone

## Describe alternatives you've considered
* N/A, new features will be added as this feature evolves
* Note this feature will "compete with" #343 for whichever feature gets completed first, because they have very similar functionality, so whoever completes it first, will have merge conflicts with the other

## Additional context
Example PDF report includes:
* Basic Car Maintenance Title
* Vehicle Name at the top
* Start and end date of all the `maintenance_events` that get exported
* Vehicle name (yes for this specific issue it'll be repeating for now)
* Notes of the maintenance events

![maintenance event export](https://github.com/user-attachments/assets/8a4218ab-3f56-485e-b880-c7de1405af3d)

**Comment by OmarHegazy93** [comment]
Hey @mikaelacaron can you assign this one to me please? Thank you!

**Comment by mikaelacaron** [comment]
Excited to see it! If you get through it super speedy, it'll be easier for the other issue I linked 👍 which would be awesome!

**Comment by rramirez-dev** [comment]
Why doesn't the Exported PDF  contain the event title.

**Comment by mikaelacaron** [comment]
> Why doesn't the Exported PDF contain the event title.

I'll make this into a separate issue! thanks for pointing it out!
