### ISSUE TITLE
FEATURE - CSV Export of Maintenance Events Only

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#343]
## Describe the feature you want the app to have that it currently doesn't
* Note that this feature and #342 will "compete" with who makes it first, because they have very similar functionality, and are going to end up having a merge conflict
* Create a CSV export of the maintenance events ordered by oldest to newest of a single vehicle
* Add a toolbar button to start the export with `square.and.arrow.up` on the leading side of the `DashboardView`
* Tapping this shows `ExportOptionsView` as a sheet
* Create a view called `ExportOptionsView` (in the `Dashboard` > `Views` directory) that's used to eventually select the options for how the CSV can be exported (making it more customizable, but for the start we'll only do specific things, listed below)
* Select the vehicle to export using a picker
* Export button (trailing toolbar button)

Full flow:
* Tap export button
* See `ExportOptionsView` as a sheet, it'll show a picker of the vehicles
* Tap an Export button (make this the trailing toolbar button of this view
* Export as described below as a CSV, that can be saved to a person's file's app or AirDropped to someone

## Describe alternatives you've considered
More features will be added to this after this issue and #342 are completed, stay tuned!

## Additional context

CSV format:
```csv
date, vehicle name, notes
```

**Comment by rramirez-dev** [comment]
You can assign this issue to me.

**Comment by mitaligondaliya** [comment]
@mikaelacaron  I'm interested in working on this issue and would like to take it on.

**Comment by mikaelacaron** [comment]
You can only work on one issue at a time, what's left for you to wrap up #338 ?

**Comment by mitaligondaliya** [comment]
> You can only work on one issue at a time, what's left for you to wrap up #338 ?

I only need to update the preview icon sizes. I'll finish that, and if this issue is still pending, I'll start working on it.
