### ISSUE TITLE
IMPROVE - `OdometerView` Preview with Mock Data

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#347]
## Describe the feature you want to improve
`OdometerView` shows the empty view as the preview, but it would be awesome to somehow pass the proper data, and/or mock it, so that we actually see example rows of data, rather than the empty screen when looking at the previews

I'm not sure what this will take, and hopefully it doesn't require too much of moving things around, but this will also help with unit testing, I'm guessing

### Empty view, in previews
![Screenshot 2024-10-21 at 1 15 36 AM](https://github.com/user-attachments/assets/eb8877b9-34fd-4eee-9788-02bfa2a3f1de)
### screenshot of the current app when you run it, and add odometer readings
I'd like to see something like this in the previews
![Simulator Screenshot - iPhone 16 Pro - 2024-10-21 at 01 15 39](https://github.com/user-attachments/assets/ae6b8861-c6e1-40fb-aa8c-dabda5d812dc)

## Describe alternatives you've considered

**Comment by mike011** [comment]
I can take care of this.
