### ISSUE TITLE
IMPROVE - Add Filter by Vehicle to `DashboardView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#354]
## Describe the feature you want to improve
Add a filter to the `DashboardView` to filter by vehicle

This is what the filter currently look likes, and add a new section that lists the vehicle names, and also `All Vehicles`, and depending on which one the user taps, it'll filter the list on the `DashboardView`

![Screenshot 2024-10-23 at 2 48 09 PM](https://github.com/user-attachments/assets/0b0a4c3b-6f3c-4f55-a21c-4a51caef9eb2)

## Describe alternatives you've considered
N/A, feel free to make suggestions!

**Comment by riddhi-b** [comment]
Hello! I am interested in contributing to this issue.

**Comment by riddhi-b** [comment]
Just wanted to let you know @mikaelacaron I am new to this repo, and I am planning on contributing as a part of a project for my Software Engineering course at UMich, if you need anything else from me or need this done by a certain time please let me know! Thank you!

**Comment by mikaelacaron** [comment]
> Hello! I am interested in contributing to this issue.

You got it!

> Just wanted to let you know @mikaelacaron I am new to this repo, and I am planning on contributing as a part of a project for my Software Engineering course at UMich, if you need anything else from me or need this done by a certain time please let me know! Thank you!


There's no specific deadline right now for this issue! You can finish it at whatever's convenient for you, be sure to check back and update your fork with changes to `dev` periodically. I'll be shipping some updates in preparation for shipping the app to the App Store soon! (but these shouldn't affect you too much)

**Comment by mikaelacaron** [comment]
Feel free to reach out or DM me anytime if you have any questions about how the repo should work / if you have any trouble! @riddhi-b

**Comment by riddhi-b** [comment]
Nevermind i don't know i I can work on this because I have a windows computer and do not have Xcode. So sorry about this!!

**Comment by mikaelacaron** [comment]
@riddhi-b thanks for trying. Yes this is an iOS development project, which requires Xcode and a Mac, is there something I can make clearer in the README to make that more understood for others?

**Comment by Abrahamiaan** [comment]
Hello, I would like to contribute to the this issue. To be honest, I've already started working on it, but I've just read that I should inform @mikaelacaron before beginning work on the issue.

**Comment by mikaelacaron** [comment]
@Abrahamiaan thank you! yes please always let me know **before** working on issues, as stated in the [README](https://github.com/mikaelacaron/Basic-Car-Maintenance?tab=readme-ov-file#contributing) and [CONTRIBUTING](https://github.com/mikaelacaron/Basic-Car-Maintenance/blob/main/CONTRIBUTING.md#start-here) files because it lets me know who is working on what, and especially during Hacktoberfest, so that two people are not working on the same issue
