### ISSUE TITLE
IMPROVE - Add Contributors Number to `ContributorsListView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#355]
## Describe the feature you want to improve
Right now you can only see everyone's username and profile pic on the `ContributorsListView`, let's also add the contributions number

Use the `contributions` property from `Contributor` model

## Describe alternatives you've considered
current view
![Screenshot 2024-10-23 at 3 20 24 PM](https://github.com/user-attachments/assets/697fe8cc-9a26-447f-b37d-2fc96a848301)

something like this, don't change the color, but just add the contributors label like shown
![Screenshot 2024-10-21 at 4 15 18 PM](https://github.com/user-attachments/assets/20111a01-644c-4720-9922-423951812bdc)

**Comment by DandyLyons** [comment]
I can take this one! 🙋🏼‍♂️
