### ISSUE TITLE
Add Setting to `SettingsView` for Imperial / Metric

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#356]
## Describe the feature you want to improve
* Add a new section to the `SettingsView` called `Units`, that is just a row that says "Units" and a picker for metric / imperial
* Set to use the user's default, based on their settings of their phone
* Depending on which one they select, make the default of the other pickers either metric or imperial
   * Adding defaults to the: `AddOdometerReadingView`, preselect miles or kilometers

## Describe alternatives you've considered
N/A, I'm open to any thoughts!

**Comment by OmarHegazy93** [comment]
Can you please assign it to me? Thanks!
