### ISSUE TITLE
FEATURE - Add `VehicleDetailView` to the `SettingsView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#357]
## Describe the feature you want the app to have that it currently doesn't
* Add a new view called `VehicleDetailView`
* When you tap on the row in the `Vehicles` section of the `SettingsView`, push a new view to show the `VehicleDetailView`
* The `VehicleDetailView` will show all the information about a vehicle
   * Right now it will have all the same info that's being shown on the `SettingsView`, so it's not super useful, but it will be in the future when photos are added

![Screenshot 2024-10-23 at 4 05 13 PM](https://github.com/user-attachments/assets/c5652dca-8f5c-48cc-95fa-1005c3aa3c2f)

## Describe alternatives you've considered
* N/A but open to ideas

## Additional context
* N/A

**Comment by isiko35** [comment]
Can you assign this issue to me please?
