### ISSUE TITLE
IMPROVE - Use async await syntax in `fetchNewestAlert` function

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#359]
## Describe the feature you want to improve
* In the `fetchNewestAlert` function in `MainTabViewModel`, change this function to be async, as opposed to using a closure 
   * `getDocuments` has an async await version, rather than closure based

## Describe alternatives you've considered
N/A

**Comment by MilanLabuss** [comment]
Hello, I would like to work on this Issue

**Comment by mikaelacaron** [comment]
you got it! @MilanLabuss
