### ISSUE TITLE
BUG -Blank sheet is presented when no maintenance events are available to export to PDF

### ISSUE THREAD

**Issue by rramirez-dev** [mikaelacaron/Basic-Car-Maintenance#363]
## Describe the bug
If there are no events to export for a vehicle you are just shown a blank sheet.

## To Reproduce
1. Launch the app
2. Tap Export icon
3. Select a vehicle that does not have any maintenance events associated with it
4. Tap Export

## Expected behavior
* You should be presented with an error message that indicates you have no events to export.

## Screenshots
* If applicable, add screenshots to help explain your problem.

## Device Info (please complete the following information):
 * Device: [e.g. iPhone16
 * OS: [e.g. iOS 18.0]
 * App Version 1.0

## Additional Context
* Add any other context about the problem here.

https://github.com/user-attachments/assets/de3c1708-7a17-46fc-9bee-a9d45ba70e80

**Comment by mikaelacaron** [comment]
@rramirez-dev actually the Share button shouldn't even show if there's no maintenance events

there's this:
```swift
if !viewModel.events.isEmpty {
   // toolbar here
}
```

are you seeing the export button, when there's no maintenance events?

**Comment by rramirez-dev** [comment]
I have updated the ticket with a video.

**Comment by mikaelacaron** [comment]
ahhhh I see what you mean, next time be sure to attach a video when filing a bug, too cause it makes it easier to understand (Added under Additional Context)

events do exist for the other vehicle, so the share button is still there, but the vehicle you chose in the picker, events don't exist, so it's blank 👍 


I'll edit your description, for what users should do to fix this, how I want it to work

**Comment by ashabooga** [comment]
Hi there! As my PR was just accepted, would it be possible for this to be assigned to me? Thanks!

**Comment by mikaelacaron** [comment]
@ashabooga yeah you can take it

The solution for this issue, is to make an `alert` that says "No events to export for this vehicle" if you tap on a vehicle, and it doesn't have any maintenance events
