### ISSUE TITLE
FEATURE - Edit Maintenance Event Details

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#4]
## Describe the feature you want the app to have that it currently doesn't
* Add a trailing swipe action to edit a maintenance event that's on the `DashboardView`
* A user would swipe left, tap on the action, and a sheet will be displayed (similar to the `AddMaintenanceView`) to edit the values of the event
* A leading navigation item will display an `Update` button which makes a call to Firebase to save the information

## Describe alternatives you've considered
* One alternative is to change the `AddMaintenanceView` to update the data, as well as add it (this requires keeping track of the state of the view whether you're in "adding" mode or "updating" mode)
   * This is harder, so I'd recommend the way described above first

## Additional context
* Don't forget the the trailing action for `Cancel` that dismisses the view

**Comment by aaronthebald** [comment]
I would like to work on this one
