### ISSUE TITLE
FEATURE - Onboarding UI

### ISSUE THREAD

**Issue by clydehenry3** [mikaelacaron/Basic-Car-Maintenance#40]
## Creating a 2-3 page onboarding experience for the user.
* These screens would present the highlighted features for users to capture before entering the app. 
* They would have text and visuals to ensure the user was informed of what to expect and to bring excitement before entering the app. 

## Alternatives
* Other alternatives would include coach marks after sign-up/login, which could hinder the User's Experience. 
* No onboarding/coach marks, but it would increase the likelihood of not using the app. 

## Additional context
* It Would be beneficial to create in Figma and integrate it into VS Code for a seamless integration 
* Figma now has developer options where I can export near to-ready/ready code.

**Comment by clydehenry3** [comment]
I would love to tackle this issue.

**Comment by horacio3m** [comment]
I would love work with u guys on this issue ![image](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/8496232/9b0e9248-5380-465b-b0c9-24ea895b9ba7)

**Comment by mikaelacaron** [comment]
@horaciomota Can you DM me your email on any social media, I'm going to start a Figma board for this! (I've been DM'ing with @clydehenry3 about this too, but I haven't set it up yet), I can do this today

**Comment by horacio3m** [comment]
@mikaelacaron ill DM u on instagram. Right Now. @horaciomota my iG

**Comment by horacio3m** [comment]
DM sent

**Comment by clydehenry3** [comment]
Awesome to have more people on board! @horaciomota @mikaelacaron

**Comment by clydehenry3** [comment]
Hey @horaciomota! I would love to connect on socials so we can talk. Thanks for popping in early on Figma

**Comment by horacio3m** [comment]
My username is horacio mota on all social platforms. You can reach out to me on Instagram at @horaciomota. @clydehenry3

**Comment by clydehenry3** [comment]
@horaciomota Sent.

**Comment by justinseal** [comment]
I was was just thinking about this. A little Onboarding to help with why a user would want to sign in and what help it might provide.

**Comment by mikaelacaron** [comment]
> why a user would want to sign in
It uses Firebase Anonymous Auth! Users don't technically need to sign in unless they want to see their data on multiple devices

**Comment by justinseal** [comment]
> > why a user would want to sign in
> > It uses Firebase Anonymous Auth! Users don't technically need to sign in unless they want to see their data on multiple devices

Got it, but there's nothing there that says they *can* do that. Yet.

**Comment by clydehenry3** [comment]
@horaciomota I tried to contact you on IG but had no success. Let me know if you want to still work on this!

**Comment by SuzGupta** [comment]
Guys, I would be happy to provide review and suggestions on this (product manager, not a designer).

**Comment by mikaelacaron** [comment]
@SuzGupta DM me your email and I'll add you to the Figma!

**Comment by maartinj** [comment]
Hi @mikaelacaron, can I try to work on Onboarding UI? Or this is done already?

**Comment by mikaelacaron** [comment]
@maartinj This isn't done yet, but also I haven't fully decided what it will look like. I have a Figma document DM me your email and you can get access to see the current progress of it and if you have any other ideas!

**Comment by maartinj** [comment]
Hi @mikaelacaron, as we discussed in Figma document, please assign me to this task. Thank you in advance! 👍

**Comment by mikaelacaron** [comment]
Thanks @maartinj can you only make the UI, but not actually connect it to anything (and don't connect it to Firebase yet) thanks!

**Comment by mikaelacaron** [comment]
Thanks @maartinj can you only make the UI, but not actually connect it to anything (and don't connect it to Firebase yet) thanks!
