### ISSUE TITLE
FEATURE - Delete a Vehicle

### ISSUE THREAD

**Issue by ayushs-2k4** [mikaelacaron/Basic-Car-Maintenance#42]
## Describe the feature you want the app to have that it currently doesn't
* Vehicle Deletion Feature

## Describe alternatives you've considered
* Currently, we cannot delete a vehicle once created. There should be a swipe to delete the vehicle feature in Settings View.

## Additional context
*N/A

**Comment by ayushs-2k4** [comment]
I will be working on feature, once I get confirmation from @mikaelacaron that a vehicle can be deleted from Vehicles list or not able to delete a vehicle is an intended feature.

**Comment by mikaelacaron** [comment]
Yes! This is an intended feature, go ahead and start it

**Comment by mikaelacaron** [comment]
This functionality already exists
