### ISSUE TITLE
BUG - Event without any Title are able to be added

### ISSUE THREAD

**Issue by ayushs-2k4** [mikaelacaron/Basic-Car-Maintenance#43]
## Describe the bug
* Events without any title and notes are able to be added.

## To Reproduce
1. Open App.
2. On Dashboard View, Tap on '+' button located in Top - Right corner.
3. Click "Add" on appeared sheet without filling any details.
4. Event without any title and notes will get added.

## Expected behavior
* "Add" button should be disabled until there is no title.

## Screenshots
* 
![Simulator Screenshot - iPhone 15 Pro - 2023-10-03 at 01 24 37](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/63922782/f4327eca-f35e-48d6-9d58-00e214d9894f)

## Device Info (please complete the following information):
 * Device: iPhone 14 Pro
 * OS: iOS 17
 * App Version: 1.0 (1)

## Additional Context
*N/A

**Comment by ayushs-2k4** [comment]
I am working on this issue.

**Comment by mikaelacaron** [comment]
@ayushs-2k4 Please only work on one issue at a time! You already started #42 You must submit a PR for that first before working on another issue.

Thank you for pointing this one out, let someone else resolve this one!

**Comment by daljeetseera** [comment]
I will take this @mikaelacaron

**Comment by daljeetseera** [comment]
It's already fixed by @mikaelacaron. Please close this issue.

**Comment by mikaelacaron** [comment]
Ahhh yes this is a duplicate of #9 and was fixed in #33
