### ISSUE TITLE
IMPROVE - move bundle id to xcconfig

### ISSUE THREAD

**Issue by mattmassicotte** [mikaelacaron/Basic-Car-Maintenance#44]
## Describe the feature you want to improve

As discussed on Mastodon (https://swiftdevs.space/@mikaelacaron/111166260903515249), sounds like it would be useful to extract the app's bundle id out to into an xcconfig. This is pretty straightforward, but since it touches the xcodeproj, may be problematic for other pending PRs.

I'm not 100% sure I understand the mechanism that is causing a particular issue on macOS. So, before doing this, I'd like to get to bottom of that first.

## Describe alternatives you've considered

Manual bundle id juggling is always an option! But it would be way nicer to move the source of truth into one, more merge-conflict-resistant location.

**Comment by mikaelacaron** [comment]
Want to pair on Tuple for this?! @mattmassicotte we can DM on a time

**Comment by mattmassicotte** [comment]
Ummm, yeah I do! DMing now

**Comment by mikaelacaron** [comment]
Completed with this commit: 94d294f3b46df2583f77e2f44daa5826196b2a0f
