### ISSUE TITLE
BUG - App crash when you delete just created maintenance

### ISSUE THREAD

**Issue by daljeetseera** [mikaelacaron/Basic-Car-Maintenance#47]
## Describe the bug
* App crash when you delete the maintenance immediately after adding/creating new maintenance.

## To Reproduce
1. Add new maintenance from dashboard.
2. Immediately delete the maintenance you just created.
3. App crash

## Expected behavior
* App should not crash at this point. The maintenance event should get deleted.

## Screenshots
<img width="1624" alt="Screenshot 2023-10-02 at 2 29 52 AM" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/54598657/890c0810-27db-4186-9ca6-4783e9286586">

## Device Info (please complete the following information):
 * Device: iPhone 15 Pro Max
 * OS: iOS 17.0
 * App Version 1.0

## Additional Context
* N/A

**Comment by daljeetseera** [comment]
I would like to fix this one @mikaelacaron

**Comment by mikaelacaron** [comment]
Go for it! haha I just found this crash too

**Comment by narendrajagne** [comment]
I am also interest on it .  assign one of them which I was commented .

**Comment by mikaelacaron** [comment]
@narendrajagne Please only comment on a single issue at a time (where someone else has not yet commented). I can only keep track of a person doing one issue, so commenting on multiple makes it difficult for me to manage.

**Comment by narendrajagne** [comment]
Noted
