### ISSUE TITLE
FEATURE - Edit Vehicle Details

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#5]
## Describe the feature you want the app to have that it currently doesn't
* Add a trailing swipe action to edit a vehcile's details that's on the `SettingsView`
* A user would swipe left, tap on the action, and a sheet will be displayed (similar to the `AddVehicleView`) to edit the values of the vehicle
* A leading navigation item will display an `Update` button which makes a call to Firebase to save the information

## Describe alternatives you've considered
* One alternative is to change the `AddVehicleView` to update the data, as well as add it (this requires keeping track of the state of the view whether you're in "adding" mode or "updating" mode)
   * The first way is easier, so I'd recommend doing that first

## Additional context
* Don't forget the the trailing action for `Cancel` that dismisses the view

**Comment by TimothyALewis** [comment]
I am going to start on this one. Just have to update Xcode and MacOS on my MacBook.

**Comment by Drag0ndust** [comment]
@NamefulEntity are already working on this issue? if not @mikaelacaron I can take it

**Comment by mikaelacaron** [comment]
@Drag0ndust Give @NamefulEntity a few days, they just commented yesterday

**Comment by TimothyALewis** [comment]
@mikaelacaron What's the deadline for submitting a PR on this feature?

**Comment by mikaelacaron** [comment]
@NamefulEntity and I chatted via DM he's going to work on this throughout the week, if he doesn't finish it by Oct 7, this is up for grabs and I'll change the assignee

**Comment by damien-rivet** [comment]
Hi @mikaelacaron,

Is this issue still available for grab or not? If it's the case I would gladly work on it.

**Comment by mikaelacaron** [comment]
This issue is being worked on by @NamefulEntity , @damien-rivet you'll have to find a different issue to work on, thank you! I'll be adding more soon

**Comment by TratonGossink** [comment]
@mikaelacaron I am starting to work on this one. If want to assign it to me that's ok. I'm gonna try and get it done this week. I know what has to be done just need to take the time to do it.

**Comment by mikaelacaron** [comment]
great thanks!

**Comment by mikaelacaron** [comment]
Closed with #269
