### ISSUE TITLE
Add GitHub Actions CI for SwiftLint

### ISSUE THREAD

**Issue by rizwankce** [mikaelacaron/Basic-Car-Maintenance#52]
## Describe the feature you want the app to have that it currently doesn't
* Since we get lot of PR and some time its easy to break the expected behaviour. To avoid it we can easily add CI (provided by GitHub Actions for free for OSS projects). CI can run tests on each PR and make sure all tests passes before we merge the new change in.

## Describe alternatives you've considered
* Alternatives would be adding via Circle CI or Bitraise but its needs extra steps and logins. Since GitHub Actions are free even for Mac OS machines its should be fine.

## Additional context
* There are lots of possibilities on this one. We can run Unit tests, UI test and even linting with swift lint and add the errors directly into the Github PR UI.

I have made the same config file and did a test run on my [repo](https://github.com/rizwankce/Basic-Car-Maintenance/pulls). Please take a look and if it aligns with your needs - I can raise a PR to this repo. Thanks for doing this awesome work.

**Comment by rizwankce** [comment]
I would like to work on this. If you are okay with it @mikaelacaron

**Comment by am2089** [comment]
If this has not been taken. I would like to work on this @mikaelacaron. Also, will you have more issues to work on?

**Comment by mikaelacaron** [comment]
@rizwankce Thank you! I was thinking on how this could work. Can you make a PR with your CI script for running SwiftLint with GitHub Actions? (putting it in the proper place in the `.github` folder)
Run it when there's a PR made to `dev` or `main` branches please

@am2089 Yes more issues to come! So many people are concurrently working right now I'm debating which ones to add without creating too many merge conflicts.
You can set the repo to "watch" it where you can customize which notifications to get when I add new issues (I think).
But I'll create a new issue, for setting up GitHub actions for running unit tests

**Comment by rizwankce** [comment]
Sure thing @mikaelacaron 

I have already made some changes on my fork. I'll raise a PR soon for review.

**Comment by mikaelacaron** [comment]
Closed with #57
