### ISSUE TITLE
GitHub Actions for Running Unit Tests

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#53]
## Describe the feature you want the app to have that it currently doesn't
* Create a CI script in the properly place in the `.github` directory for running a CI script to run the unit tests
* Trigger the script to run when there is a PR to dev or main, and it can be run manually

## Describe alternatives you've considered
* I don't believe you can test this at all, on the repo because it needs to be approved my @mikaelacaron , you may need to create it in your own project, run it and test it, and then once you know this syntax is right, make a PR and Mikaela can try it on this repo

## Additional context
* Only run the unit tests. I'll make a different issue for running UI tests

**Comment by mikaelacaron** [comment]
@am2089 if you want to work on this still, comment here and I can officially assign it to you!

**Comment by am2089** [comment]
Yes I would love to!

**Comment by hanhqvu** [comment]
Hi again @mikaelacaron,

Since the original assignee removed themselves, can I tackle this next once my other PR is merged?

**Comment by mikaelacaron** [comment]
Yes! you got it! See previous PRs, there were some issues running the unit tests from GitHub actions, it may be possible to run this from fastlane instead, possibly collaborating with the contributor on #54 may help

**Comment by hanhqvu** [comment]
@mikaelacaron I tried it but there were some error about device large not being available.
During research, I came upon this issue: https://github.com/actions/runner-images/issues/551
This seems to be an issue related to Github Action itself so moving to Fastlane would be a better option imo.

**Comment by mikaelacaron** [comment]
Sounds good! Let's do it, using fastlane!
We don't really have to install anything into the project right? It's more about installing fastlane on a person's individual machine, if they want to run a lane? right?

**Comment by hanhqvu** [comment]
That's correct! Fastlane also have setup to integrate with Github Action.
I will try to do that and let you know the result.

**Comment by mikaelacaron** [comment]
Sounds good thanks! Feel free to DM me on [social media](https://mikaelacaron.com/links), if you need me to do something specific with the repo setup, if needed

**Comment by hanhqvu** [comment]
I was able to get it to work with both Xcode CLI & Fastlane but considering Fastlane has easier to understand syntax,
I proceeded with Fastlane.
