### ISSUE TITLE
GitHub Actions for Running UI Tests

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#54]
## Describe the feature you want the app to have that it currently doesn't
* Create a CI script in the properly place in the `.github` directory for running a CI script to run the UI tests
* Trigger the script to run when there is a PR to `dev` or `main`, and it can be run manually
* I'm not entirely sure if this is possible in GitHub Actions, but if not, I'd prefer to use Fastlane
   * Creating a fastlane lane that would run the UI tests, and could be triggered by a GitHub action
   * If using fastlane, the README and CONTRIBUTING should be updated as needed

## Describe alternatives you've considered
* I don't believe you can test this at all, on the repo because it needs to be approved my @mikaelacaron , you may need to create it in your own project, run it and test it, and then once you know this syntax is right, make a PR and Mikaela can try it on this repo

## Additional context
* Only run the UI tests, #53 covers creating a script for running the unit tests

**Comment by am2089** [comment]
Would like to work on this one!

**Comment by mikaelacaron** [comment]
@am2089 only a single issue at a time! Thanks I just assigned you to #53

**Comment by am2089** [comment]
Thanks!

**Comment by Javier1019** [comment]
Hey @mikaelacaron can you assign this to me?

**Comment by mikaelacaron** [comment]
You got it! @Javier1019 I'm not completely sure if this only works in GitHub Actions, or if we might also need fast lane, to actually run the UI tests, and then that is triggered from GitHub Actions, it'll take some investigation

**Comment by Javier1019** [comment]
All is good learning is part of the equation.

**Comment by Javier1019** [comment]
Hey @mikaelacaron so after a few searches it's the second guess you mentioned. We can make a GitHub Action that runs a Fastlane lane and runs in the lane. I'll keep on researching on this approach and keep you posted.

**Comment by Javier1019** [comment]
@mikaelacaron Have we established code coverage and is there anything I should know ahead of time?

**Comment by Javier1019** [comment]
Definitely the way that I see this is XCTest script and use fastlane to make it run in a lane also add code coverage to do a scan app wise.

**Comment by mikaelacaron** [comment]
> Have we established code coverage
in what way? like a target % code coverage number? No there isn't

The code coverage, would that show in GitHub? That may go with #71

**Comment by mikaelacaron** [comment]
@Javier1019 Now that we've merged #123 which uses fastlane, this should also use fastlane for running the UI tests, thanks!

**Comment by mikaelacaron** [comment]
@Javier1019 
Thanks for wanting to contribute! Hacktoberfest ended on October 31, if you can still finish this issue by Saturday November 4, I’ll accept it, but otherwise after that I’ll be un-assigning all issues and cleaning up the code to ship this app to the App Store

**Comment by mikaelacaron** [comment]
Fixed with #194
