### ISSUE TITLE
GitHub Action for Creating DocC Documentation

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#55]
## Describe the feature you want the app to have that it currently doesn't
* Following [this tutorial](https://www.kodeco.com/40047657-docc-tutorial-for-swift-automating-publishing-with-github-actions) create a script that will automatically build the DocC documentation for this project and publish it to GitHub Pages for the project
* Try to do this in a public repo from the test code, and link it below in a comment, once @mikaelacaron looks at that, you can probably then create the actual CI script in the right place in the `.github` directory of this project, but nothing will happen because it has to actually be set up by @mikaelacaron 

## Describe alternatives you've considered
* I'm open to other ideas for automatically building the DocC documentation

## Additional context
* Discuss below, but I'm not sure exactly when this should be ran, on a merge of any branch into `dev`? Because it wouldn't make sense for new docs to be published on a PR (this could change docs for each person's PR, which isn't a source of truth until it's merged)
   * Let me know your ideas before creating a PR

**Comment by rizwankce** [comment]
Ideally this should run only when there is the documentation change. GitHub Actions provides ways to only select some paths or files and when it's changed run an action. I guess this would be good solution for this issue.

**Comment by mikaelacaron** [comment]
> Ideally this should run only when there is the documentation change

true, but any of the Swift files can contribute to the documentation changing. Technically it probably could run on any merge to `dev`, because that would mean the code has changed, and then we'd want the latest documentation?
What do you think?

**Comment by rizwankce** [comment]
I agree. We can target for main and dev branches and build documentation.

**Comment by mikaelacaron** [comment]
@rizwankce do you want to be assigned this issue?

**Comment by rizwankce** [comment]
@mikaelacaron yes please.

**Comment by mikaelacaron** [comment]
@rizwankce you may need more info from me to setup up GitHub pages on the repo. Please [DM me](https://mikaelacaron.com/links) on social media for this (as opposed to commenting here) to get that all set up

I'm thinking you could follow the tutorial with the example project on a public repo and that could help me see what changes may be needed
