### ISSUE TITLE
FEATURE - Add Localization Comments to the `DashboardView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#59]
## Describe the feature you to improve
* Add localization comments to `DashboardView`

## Describe alternatives you've considered
* N/A

## Additional context
* Describe what the string is about, a button to do XYZ, a tab item label showing ABC info. The localization comment is a short string to help people localize the strings in the app

**Comment by ThiernoDiallo2018** [comment]
Would like to work on this

**Comment by ThiernoDiallo2018** [comment]
Hey Mikaela - free up this issue so someone can knock it out this month. Backed up with a bunch of things right now.

**Comment by hartti** [comment]
Is this available to work on? If yes, I'll work on this.

**Comment by mikaelacaron** [comment]
@hartti yes! Any issue with no assignee and the proper label and you can only work in a single issue at a time

**Comment by hartti** [comment]
I have now added the comments. Next step: figuring out how to do the pull request... I'll work on that later today.

**Comment by mikaelacaron** [comment]
@hartti See my [livestream](https://www.youtube.com/live/-rYYKXrCyro?si=NZkeFLW-u8QXG6JA), I go through the process of making a PR
