### ISSUE TITLE
FEATURE - Use `NavigationSplitView` rather than `TabView` for iPad

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#6]
## Describe the feature you want the app to have that it currently doesn't
* Using a `NavigationSplitView` would look better on iPad rather than a `TabView`
* Make this change at the `BasicCarMaintenanceApp` level depending on the OS

## Describe alternatives you've considered
* Comment any other alternatives you think would look good as well (comment if you're going to do something other than `NavigationSplitView`)

## Additional context
* N/A

**Comment by AndreasInk** [comment]
I can take this one if it's still open 😀

**Comment by mikaelacaron** [comment]
@AndreasInk are you still working on this? If not, I can assign it to someone else, and you're welcome to work on a different issue

**Comment by AndreasInk** [comment]
@mikaelacaron thanks for checking in, I completed this locally the day I took the task but forgot to push and open a PR, I'll do this later tonight, the alarm is set to remind me :)

**Comment by mikaelacaron** [comment]
lol you could've been one of the first contributors

if you haven't updated your branch since you did this, you'll 100% need to do that and probably resolve conflicts before making the PR

**Comment by AndreasInk** [comment]
lol yeah I can imagine that's the case, luckily it's will not be a huge PR

**Comment by darrengillman** [comment]
@mikaelacaron as per comment on other issue, happy to pick this up and see it home if it helps still?
Would need your guidance on how to get the changes from the PR into my repo though.

**Comment by mikaelacaron** [comment]
You got it! Look at the changes of the other PR #178 and just manually copy / paste it, that's the easiest

**Comment by mikaelacaron** [comment]
@darrengillman any update on this? if not I'll be un-assigning you, thank you!

**Comment by darrengillman** [comment]
I misunderstood your last message!  I thought you meant you already had it
in hand and were going to tidy it up as part of your final wrap up before
pushing to the App Store.

I can sort it out if you'd like me to, but might not be before the weekend.

**Comment by mikaelacaron** [comment]
Sorry for the miscommunication!
You said: Would need your guidance on how to get the changes from the PR into my repo though.
and I mentioned:
> Look at the changes of the other PR https://github.com/mikaelacaron/Basic-Car-Maintenance/pull/178 and just manually copy / paste it, that's the easiest

As in that's what needed to finish this issue

Can you finish this by December 13?

**Comment by darrengillman** [comment]
We had an email exchange after that.  But no worries, sure I can get it
done by then.

Assuming I’m not buried in elves with Advent of Code 🙂

Darren Gillman
e: ***@***.***
m: 07770 661594

**Comment by mikaelacaron** [comment]
wait which email exchange....? I don't think I've emailed you before? @darrengillman

**Comment by darrengillman** [comment]
I think there are some inconsistencies in the original PR, so it's more than a copy / paste and fix the style / lint it change, and I'm not going to have the time to get into the detail this week.  So going to un-assign myself rather than hold up your schedule.

**Comment by mikaelacaron** [comment]
@darrengillman thank you!! yeah I guessed changes were going to be needed, because the original PR was from a while back ago

@windrunner21 if you were looking for another issue, this one would be great!

**Comment by windrunner21** [comment]
Sure, just to clarify you would like to use NavigationSplitView everywhere instead of TabView for iPad? Other than that I can take the task! @mikaelacaron

**Comment by mikaelacaron** [comment]
@windrunner21  The word "everywhere" here is tripping me up haha

I want to use the `NavigationSplitView` on iPad, because the 3 tabs at the bottom just feel kinda clunky to me

So it would use the Split View when it's in landscape or portrait

**Comment by windrunner21** [comment]
@mikaelacaron I've just started working on the feature, hope it's not a problem. When is the deadline? 😅 I wanted to ask you one question - should NavigationSplitView work on iPad and Mac as well, or only iPads?

**Comment by mikaelacaron** [comment]
Only do iPad right now, the Mac target doesn't even build at the moment, so don't worry about it
@windrunner21 could you finish this by next week Dec 22?

**Comment by windrunner21** [comment]
@mikaelacaron opened a PR already!
