### ISSUE TITLE
FEATURE - Add Localization Comments to the `SettingsView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#60]
## Describe the feature you to improve
* Add localization comments to `SettingsView`

## Describe alternatives you've considered
* N/A

## Additional context
* Describe what the string is about, a button to do XYZ, a tab item label showing ABC info. The localization comment is a short string to help people localize the strings in the app

**Comment by johnolwamba** [comment]
Hi @mikaelacaron, I would like to work on this issue

**Comment by mikaelacaron** [comment]
You got it!
