### ISSUE TITLE
FEATURE - Add Localization Comments to the `AddMaintenanceView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#61]
## Describe the feature you to improve
* Add localization comments to `AddMaintenanceView`

## Describe alternatives you've considered
* N/A

## Additional context
* Describe what the string is about, a button to do XYZ, a tab item label showing ABC info. The localization comment is a short string to help people localize the strings in the app

**Comment by infiniteltd** [comment]
I would love to work on this issue.

**Comment by infiniteltd** [comment]
Thanks

**Comment by hanhqvu** [comment]
hi @mikaelacaron

if this is still open, I would like to work on this issue

**Comment by mikaelacaron** [comment]
It's all you! considering the last person unassigned themselves @hanhqvu
