### ISSUE TITLE
FEATURE - Add Link to Privacy Policy

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#62]
## Describe the feature you want the app to have that it currently doesn't
* Add a new row in the `SettingsView` right above the version number (but in the same section)
* Create a row that when tapped, the privacy policy will be opened in the user's default browser

Privacy policy link: `https://github.com/mikaelacaron/Basic-Car-Maintenance-Privacy`

## Describe alternatives you've considered
* N/A

## Additional context
* Add any other context or screenshots about the feature request here.

**Comment by shreyanshig** [comment]
Hello @mikaelacaron, assign this task to me

**Comment by Basavarajakjbasuu** [comment]
Hai @mikaelacaron  Can I work on this issue, could you please assign to me

**Comment by daljeetseera** [comment]
I will take it @mikaelacaron

**Comment by mikaelacaron** [comment]
@daljeetseera this issue is labeled `first-timers-only` it is specifically for someone brand new to Hacktoberfest who hasn't completed an issue before.
You've already done #58 I'd like to assign this to someone else, thank you

**Comment by Himanshu200316** [comment]
I would like to contribute, but can i get some help on where to start this with?

**Comment by mikaelacaron** [comment]
@Himanshu200316 you can do it! Look at the `SettingsView` and how the link to the GitHub repo works

**Comment by Himanshu200316** [comment]
> @Himanshu200316 you can do it! Look at the `SettingsView` and how the link to the GitHub repo works

Thanks i will try my best!

**Comment by Adnaanlegend** [comment]
@mikaelacaron Can i look into this or is this issue taken? 
PS- I am new to this.

**Comment by mikaelacaron** [comment]
@Himanshu200316 is working on it right now, but if there's not a PR up in the next 3 days, feel free to comment again and I can assign it to you @Adnaanlegend 

Until then you can find another issue labeled `first-timers-only`

**Comment by Adnaanlegend** [comment]
@mikaelacaron Thank you so much for the heads up. I am going to circle back to this.

**Comment by mikaelacaron** [comment]
@Adnaanlegend any issue without an assignee is available. If there is an assignee, assume it's being worked on

**Comment by Himanshu200316** [comment]
Sorry! Mike due to some personal circumstances i failed to complete the task. Im sorry!

**Comment by mikaelacaron** [comment]
That's okay! Thank you for trying! You're welcome to comeback later in the month and contribute if you'd like

**Comment by AnkitAnandMastery17** [comment]
Hey @mikaelacaron , Is this issue open? I want to work on this issue.

**Comment by mikaelacaron** [comment]
@AnkitAnandMastery17 Yes go for it!

**Comment by Adnaanlegend** [comment]
@mikaelacaron Missed it by that much.

**Comment by Himanshu200316** [comment]
> That's okay! Thank you for trying! You're welcome to comeback later in the month and contribute if you'd like

Thank you ! T^T

**Comment by mikaelacaron** [comment]
So close @Adnaanlegend thanks for wanting to contribute! New issues are added throughout the month

**Comment by AnkitAnandMastery17** [comment]
Sorry, but I am using Windows, not Ios or Mac. You can assign someone else.

**Comment by Oksenoyt** [comment]
I would indeed like to work on this! Thanks @mikaelacaron !
