### ISSUE TITLE
BUG - Delete Maintenance Event Not Removed From Array

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#63]
## Describe the bug
* The maintenance event does the swipe to delete, but it actually isn't being removed from the `events` array and

## To Reproduce
* Make sure you have an event created
1. Swipe left to delete the event
2. See the error, the event animates like it deletes, but then is still there

* Switching tabs and coming back to Dashboard, you can see that it is deleted from Firebase, but it doesn't remove from the array, staying on the `DashboardView`

## Expected behavior
* Swipe to delete, the event is removed from the `events` array and from Firebase

## Screenshots

https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/be9b9c4b-9f86-451f-9a00-f2eebcb01f1b

## Device Info (please complete the following information):
 * Device: iPhone 15 Pro Simulator
 * OS: iOS 17.0
 * App Version v1.0 (1)

**Comment by josephnoir** [comment]
Hi Mikaela, I would like to give this a try.

**Comment by mikaelacaron** [comment]
@josephnoir you can do it! 👍

**Comment by josephnoir** [comment]
I'm finally looking into this. When I open `DashboardView.swift` the Preview crashes and only shows a red X. The shell prints this:

```
No user signed in. Trying to sign in anonymously.
No user signed in. Trying to sign in anonymously.
User is signed in
```

Is that the expected behavior?

**Comment by mikaelacaron** [comment]
It's not *expected* but at the moment previews are crashing. Run the app on the simulator
