### ISSUE TITLE
IMPROVE - Alphabetical Imports

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#64]
## Describe the feature you want to improve
* Go through all of the Swift files and put all the imports in alphabetical order

## Describe alternatives you've considered
* N/A

**Comment by ayushs-2k4** [comment]
I would like to work on this @mikaelacaron.

**Comment by mikaelacaron** [comment]
@ayushs-2k4 you have already done #32 this issue is labeled `first-timers-only` and is specifically for someone brand new to Hacktoberfest and hasn't worked on an issue before. Please look at other issues thank you.

**Comment by ampsonic** [comment]
I’d like to take this one if it’s still available.

**Comment by AbhishekChoudhary11** [comment]
I'm first timer and I want to work on it

**Comment by mikaelacaron** [comment]
@AbhishekChoudhary11 this issue has already been assigned to @ampsonic There's another `first-timers-only` issue available, but I'll be creating new issues everyday!
You can also play with the app and if you find a bug, you can create a new issue too!
