### ISSUE TITLE
FEATURE - Home Screen Quick Action

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#65]
## Describe the feature you want the app to have that it currently doesn't
* Create a [Home Screen Quick Action](https://developer.apple.com/documentation/uikit/menus_and_shortcuts/add_home_screen_quick_actions) that will open the `AddMaintenanceView` to easily add a maintenance event

## Describe alternatives you've considered
* N/A

## Additional context
* Possibly work on how you can make this code testable and easy to use later on App Intents and Siri Shortcuts

**Comment by OmarHegazy93** [comment]
Hi @mikaelacaron, I'd like to work on this one
