### ISSUE TITLE
IMPROVE - configs for widget signing

### ISSUE THREAD

**Issue by mattmassicotte** [mikaelacaron/Basic-Car-Maintenance#67]
## Describe the feature you want to improve

Signing of the newly added Widget target doesn't use the user xcconfig file. This is because the user config applies only to a single target (the app) and not the project as a whole.

A solution, though definitely not the only, is to move to an arrangement where the user-specific information (currently in Basic-Car-Maintenance.xcconfig) is imported into the project-wide xcconfig. This will allow you to apply the same signing information to all targets, which is almost certainly what you want.

**Comment by mikaelacaron** [comment]
Fixed with #86
