### ISSUE TITLE
GitHub Actions for Running Code Coverage

### ISSUE THREAD

**Issue by elmoritz** [mikaelacaron/Basic-Car-Maintenance#71]
## Describe the feature you want the app to have that it currently doesn't
Create a CI script in the properly place in the .github directory for running a CI script to run the code coverage workflow
Trigger the script to run when there is a PR to dev or main, and it can be run manually

## Describe alternatives you've considered
I have not considered any alternatives, I just read through the issues and found a few covering tests and Github Actions.
I do love to have unit test in a project, but there is never a good way to motivate contributors to add them to the PR.

## Additional context
It would be great if there would be a blocker to prevent a PR from merging if the coverage has not increased (might be determine via a threshold)
I already looked into the issue and for most projects you can not use any online tools, but for this one it might be very easy and nice to use [codecove.io](https://about.codecov.io).

In my previous research I already stumbeld upon this nice post [codecov.io-post](https://about.codecov.io/blog/code-coverage-for-ios-development-using-swift-xcode-and-github-actions/)

**Comment by elmoritz** [comment]
@mikaelacaron this issue might be also very nice for first-timers.
We have to find out, if you as the repo-owner has to add it to codecov.io

**Comment by mikaelacaron** [comment]
This would be great! Does this only show in codecov.io or would it show somewhere in GitHub too?
[This tutorial](https://about.codecov.io/blog/code-coverage-for-ios-development-using-swift-xcode-and-github-actions/) looks helpful!

**Comment by elmoritz** [comment]
The goal of this issue would be to have a report on every PR to encourage the contributors of increasing the test coverage, with simple tests.

As I looked through the research material I collected and one thing that could help this a lot is to have a *.xctestplan-file.
Might be nice to have one for Unit tests and one for UITests

**Comment by mikaelacaron** [comment]
@elmoritz Is the test plan file one that I should create as the maintainer or is it fine for contributors to add?

**Comment by elmoritz** [comment]
@mikaelacaron sorry I missed you response here.
The Testplans can be created by anyone, does not have to be you.

When I open the project right now an go to the "test navigator" it already has a testplan, but I'm not sure if you can use that one created from xcode in the CI via fastlane?

I only ever had to create one and place it near the fastlane file to access it quickly for all the tests to run

**Comment by mikaelacaron** [comment]
Fixed with #194
