### ISSUE TITLE
IMPROVE - Remove rules from `disabled_rules` in SwiftLint configuration file

### ISSUE THREAD

**Issue by abhinaypratap** [mikaelacaron/Basic-Car-Maintenance#72]
## Describe the feature you want to improve

Sometimes it is almost impossible to avoid `SwiftLint` warnings and therefore we ignore those rules in the project altogether, but that is something we do when we integrate `SwiftLint` in an existing/legacy project having thousands of items in `Compile Sources`.

At this moment, we have only 12 items in our `Compile Sources`. If we start ignoring and putting rules into `disabled_rules`, eventually we will arrive at a point where we will have tens of thousands of `SwiftLint` violations.

Right now, the `disabled_rules` contains:
```yml
disabled_rules:
  - colon
  - comma
  - control_statement
  - type_name
  - trailing_whitespace
  - identifier_name
  - empty_parentheses_with_trailing_closure
```

If I enable all 7 of these rules, there are around 90 violations (which can be easily fixed).

If we look at these 7 rules, the default configuration for all of them are quite awesome practically, except `identifier_name`. And we have seen in larger projects that `identifier_name` can be configured as:
```yml
identifier_name:
  excluded:
    - id
    - db
    - URL
```

**Comment by mikaelacaron** [comment]
I think this is a good idea, and like you mentioned, is great to do early. I want to wait until next week to do this issue, with the amount of people adding to the code base right now and avoiding merge conflicts

I'm only avoiding new SwiftLint warnings, at the moment, but slowly adding individual tasks to resolve each SwiftLint warning could work. But I don't want anyone to start this yet.
