### ISSUE TITLE
IMPROVE - find an easy to use Architecture for the whole app

### ISSUE THREAD

**Issue by elmoritz** [mikaelacaron/Basic-Car-Maintenance#76]
## Describe the feature you want to improve
It would be nice if the whole app uses one Architecture
Architectures that come to mind and might be easy enough for beginners:
- MVC (Model-View-Controller)
- MVVM (Model-View-Viewmodel)
- TCA (The Composable Architecture)
- ....

## Describe alternatives you've considered
This might not be the easiest Task, but could improve future development and Testing!!!!

**Comment by mikaelacaron** [comment]
I am using MVVM (and the app is really like 2 screens at the moment), what about the current architecture do you find confusing? Or is not following MVVM?

**Comment by mikaelacaron** [comment]
@elmoritz ^^ question

**Comment by elmoritz** [comment]
I was thinking more of the purpose of testing and mocking.
I know it is not a big app, but would probably improve the possibility to test as much as possible.

But this was just a thought.

**Comment by mikaelacaron** [comment]
In what way do you think the project isn't set up yet to test it? @elmoritz

**Comment by elmoritz** [comment]
@mikaelacaron you are right. I had another look at the few ViewModels, which should actually be testes.
You are right for the Size of this project and the few Classes to test we do not need to change Anything.
It might be a little bit more difficult to test everything, but that is all.

I will close this issue, since it is no longer relevant
