### ISSUE TITLE
FEATURE - Add Bar Button Item to Order Events by Date

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#8]
## Describe the feature you want the app to have that it currently doesn't
* Add a trailing bar button item to the `DashboardView` to order the maintenance events by date when tapped
* The button will sort the events when tapped by:
   * Oldes to newest
   * Newest to oldest
   * "Custom" This is the original choice (the order it's downloaded from Firebase)

## Describe alternatives you've considered
* Another way to implement this is to tap on the trailing button and have a context menu pop up, that will show "Oldest to Newest," "Newest to Oldest," and "Custom" and then depending on which the user selects, it orders the events

## Additional context
* This should only requre ordering the events that are fetched when the app loads, the actual Firebase query shouldn't need to change

**Comment by ayushs-2k4** [comment]
Can I work on this?

**Comment by mikaelacaron** [comment]
> Can I work on this?

Yes, but not before your PR is closed #26

If someone else wants to work on this, and #26 is still open, please comment that you want to work on this issue!

**Comment by DannyBehar** [comment]
Is this issue still available to take? If so I can take it.

**Comment by ayushs-2k4** [comment]
Please review my PR #32 and if that is good, assign this to me

**Comment by mikaelacaron** [comment]
I'm going to hand this one to @DannyBehar Because I still haven't reviewed your PR #32 @ayushs-2k4 Can you please choose another issue? Thanks!

**Comment by mikaelacaron** [comment]
Closed with #41
