### ISSUE TITLE
Interactive Tutorial for Getting Started

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#85]
## Describe the feature you want the app to have that it currently doesn't
* Create an [interactive tutorial](https://www.swift.org/documentation/docc/tutorial-syntax) for getting started with project, this should include how to set up the project using the commands in the [README](https://github.com/mikaelacaron/Basic-Car-Maintenance#readme) and [CONTRIBUTING](https://github.com/mikaelacaron/Basic-Car-Maintenance/blob/main/CONTRIBUTING.md) file

## Describe alternatives you've considered
* N/A

## Additional context
* This issue is only about the "getting started" what a contributor would look at if they were getting started to build the project for the first time

**Comment by ampsonic** [comment]
I’d like to take this one

**Comment by mikaelacaron** [comment]
@ampsonic Great! But don't start on it yet! haha I gotta fix the project first, I'll post in [Discussions](https://github.com/mikaelacaron/Basic-Car-Maintenance/discussions) when I've finally got it done, thanks! You can figure out what you want to write and do some markdown, but I will be changing a lot of files tonight, so I wouldn't do anything you don't want to lose

**Comment by ampsonic** [comment]
Sounds good I’ll hold tight!

**Comment by mikaelacaron** [comment]
@ampsonic You are good to go! Thanks for waiting! You may want to delete your local repo and follow the steps again, (but technically you should be good if you just pulled from `dev`)

**Comment by mikaelacaron** [comment]
@ampsonic are you still working on this? If not, I can assign it to someone else, and you're welcome to work on a different issue

**Comment by ampsonic** [comment]
Yes indeed, should have something done today!

**Comment by ampsonic** [comment]
@mikaelacaron When I clone my fork using the github command line, the upstream repo is automatically set. Are you ok if I leave that step out, or are there scenarios where it will be required? 

![CleanShot 2023-10-16 at 10 09 20@2x](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/25410020/4a43bfd8-6e77-4d8a-8816-573908c93f1a)
![CleanShot 2023-10-16 at 10 10 02@2x](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/25410020/2c81cdff-0af3-46e5-84c3-0cfb5ab32ec5)

**Comment by mikaelacaron** [comment]
You could add "if needed" but I think maybe this is done now by default

You could google around and check

**Comment by mikaelacaron** [comment]
@ampsonic also note that, that is with the GitHub command line, doing a regular `git clone` could have different behavior
