### ISSUE TITLE
FEATURE - Firebase Analytics Screen Name

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#89]
## Describe the feature you want the app to have that it currently doesn't
* Add this modifier `.analyticsScreen(name: "\(Self.self)")` to these views in the app
* You will need to `import FirebaseAnalyticsSwift` on all these files (put the imports in alphabetical order)
* Make this the first modifier for the `body`

## Describe alternatives you've considered
* N/A

## Additional context
* [ ] `DashboardView`
* [ ] `AddMaintenanceView`
* [ ] `EditEventDetailView`
* [ ] `SettingsView`
* [ ] `AddVehicleView`
* [ ] `ContributorsListView`
* [ ] `AuthenticationView`

**Comment by ahmdyasser** [comment]
@mikaelacaron Can I work on that?

**Comment by ahmdyasser** [comment]
@mikaelacaron I can't run the project locally. I tried to follow the steps in the README.md but issue persists. 

<img width="364" alt="image" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/42544598/d8a9210b-9e62-4496-935f-e6096b0379c3">

**Comment by mikaelacaron** [comment]
You need to follow the steps again, you did not replace the values in the `Basic-Car-Maintenance.xcconfig` with your information

**Comment by ahmdyasser** [comment]
@mikaelacaron Free Apple Developer Account doesn't have Team ID.

**Comment by mikaelacaron** [comment]
Ahhhh interesting, I didn't realize this, if you go here, there still isn't one?
https://developer.apple.com/help/account/manage-your-team/locate-your-team-id/

**Comment by ahmdyasser** [comment]
@mikaelacaron nope

**Comment by mikaelacaron** [comment]
Building for iOS, you still can't run? after changing the values in the `xcconfig`? Try changing the bundle ID, but leave the development team blank, you should be able to run on the simulator

**Comment by anupdsouza** [comment]
@ahmdyasser you just need to copy the config file as mentioned in the readme. You don't have to change anything in order to run it in the simulator.

**Comment by anupdsouza** [comment]
Hey @mikaelacaron, can I take this up? Seems to be stuck in limbo.

**Comment by mikaelacaron** [comment]
You did #148, and I labeled this one `first-timers-only` so it's only reserved for people who haven't committed to the repo yet

@ahmdyasser Did you figure this out? If not, I can unassign it to you, if you don't want to work on it anymore

**Comment by mitaligondaliya** [comment]
@mikaelacaron If this isn't fixed and no one is working on it currently, I would like to work on this. Can you please assign it to me?

**Comment by mikaelacaron** [comment]
@mitaligondaliya I labeled this one `first-timers-only`, so it's only reserved for people who haven't contributed to the codebase yet, and you just did #190

**Comment by ashwindsilva** [comment]
@mikaelacaron I would like to work on this. Could you please assign it to me?
