### ISSUE TITLE
IMPROVE - Error Handling Adding a Maintenance Event

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#9]
## Describe the feature you want to improve
* Add error handling so that a user can not create a new maintenance event with an empty title
*  If the user tries to create a new event with an empty title, an alert should show saying "You can't have an empty title"

## Describe alternatives you've considered
* Possibly a simpler solution is to gray out the "Add" button, until the user has filled in the title, rather than showing an alert

**Comment by narendrajagne** [comment]
Hi Sir, can please assign me this issue ?

**Comment by narendrajagne** [comment]
Hii, Can you assign me this issue ?

**Comment by mikaelacaron** [comment]
Closed with #33
