### ISSUE TITLE
Document the `Contributor` Struct

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#91]
## Describe the feature you want the app to have that it currently doesn't
* Document the `Contributor` struct using the documentation comments so that it will show up in the DocC documentation
Some info [here](https://docs.github.com/en/free-pro-team@latest/rest/repos/repos?apiVersion=2022-11-28#list-repository-contributors), but not super descriptive

## Additional context
* Example for one `htmlURL`

```swift
/// The ``URL`` to the user's profile.
let htmlURL: String
```

**Comment by abhinaypratap** [comment]
Hi @mikaelacaron 
Could you please assign me any of these issues:

#89 
#91
#92

**Comment by mikaelacaron** [comment]
@abhinaypratap Please only comment on the one you want to work on, that's how I can assign them, for your username to show up in the drop down for assignees, do you have a specific one of those you want to work on?

**Comment by abhinaypratap** [comment]
Okay, I'd like to work on this one (#91).

**Comment by mikaelacaron** [comment]
Awesome assigned!

**Comment by abhinaypratap** [comment]
Thank you!
