### ISSUE TITLE
FEATURE - Link to Maintainer

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#92]
## Describe the feature you want the app to have that it currently doesn't
* Create a new row in the `SettingsView` in the 1st section, right after the "GitHub Repo" and before the "Request a New Feature," link to Mikaela's GitHub Profile
* Label the row: `🦄 Mikaela Caron - Maintainer`
* Link to: `https://github.com/mikaelacaron`

## Describe alternatives you've considered
* N/A

## Additional context
* This allows anyone to be able to contact Mikaela directly about the project if needed

**Comment by johnolwamba** [comment]
Hi @mikaelacaron, can I work on this issue?

**Comment by johnolwamba** [comment]
Hi @mikaelacaron, should the unicorn be part of the name or be an icon similar to the bug and GitHub icons?

**Comment by mikaelacaron** [comment]
@johnolwamba it should be part of the name, just the emoji
