### ISSUE TITLE
FEATURE - Add Navigation Title to `AddVehicleView`

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/Basic-Car-Maintenance#94]
## Describe the feature you want the app to have that it currently doesn't
* Add a navigation title to the `AddVehicleView`
* Title it: `Add Vehicle`, and be sure to add a localization comment

## Describe alternatives you've considered
* N/A

## Additional context
* No navigation title shown
![simulator_screenshot_5B17D253-EDDE-4BC8-B405-8833F8733022](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/1821626a-cac5-4a22-8c38-d82ebc201987)

**Comment by achi113s** [comment]
I’ll take care of it! 🫡

wait nvm just saw its first timers only!

**Comment by hoangatuan** [comment]
Hi @mikaelacaron, I can help with this feature.

**Comment by mikaelacaron** [comment]
@hoangatuan it's all yours!

@achi113s thank you for understanding it's `first-timers-only` ❤️
